//! CLDR `en` locale content — GENERATED by `tools/gen_cldr_en.py`, do not edit.
//!
//! Source: CLDR release 47.0.0 (https://github.com/unicode-org/cldr-json, tag 47.0.0),
//! files (sha256, first 16 hex):
//!   ca-gregorian.json        0d0eaf3fa57a60e2
//!   dayPeriods.json          e92f73e202fc5ec7
//!   dateFields.json          4fcaa5f74d743a0b
//!   numbers.json             0fb0816663dd8be9
//!   units.json               334e097aaf5ed98f
//!   listPatterns.json        e68b0612a0c0f129
//!   localeDisplayNames.json  6023ee09d58ec7ca
//!
//! zipp's `[[AvailableLocales]]` is exactly `["en", "en-US"]`, so this file is
//! the engine's ENTIRE locale content: shipping it makes that advertised claim
//! true end to end instead of approximately true. Nothing here is invented — a
//! value absent from CLDR is absent here, and the callers fall back rather than
//! guess. CLDR 47 is the release ICU 77 / node 24 carry, which is what makes
//! `node` an exact oracle for these values (see `tools/gen_cldr_en.py`).
#![allow(dead_code)]

/// The CLDR release these tables were cut from.
pub const CLDR_VERSION: &str = "47.0.0";

// ── gregorian calendar names (ca-gregorian.json → dates.calendars.gregorian)
pub const MONTHS_WIDE: [&str; 12] = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
pub const MONTHS_ABBR: [&str; 12] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
pub const MONTHS_NARROW: [&str; 12] = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"];
pub const MONTHS_SA_WIDE: [&str; 12] = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
pub const MONTHS_SA_ABBR: [&str; 12] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
pub const MONTHS_SA_NARROW: [&str; 12] = ["J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D"];
pub const DAYS_WIDE: [&str; 7] = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
pub const DAYS_ABBR: [&str; 7] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
pub const DAYS_SHORT: [&str; 7] = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
pub const DAYS_NARROW: [&str; 7] = ["S", "M", "T", "W", "T", "F", "S"];
pub const DAYS_SA_WIDE: [&str; 7] = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
pub const DAYS_SA_ABBR: [&str; 7] = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
pub const DAYS_SA_SHORT: [&str; 7] = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"];
pub const DAYS_SA_NARROW: [&str; 7] = ["S", "M", "T", "W", "T", "F", "S"];
pub const QUARTERS_WIDE: [&str; 4] = ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"];
pub const QUARTERS_ABBR: [&str; 4] = ["Q1", "Q2", "Q3", "Q4"];
pub const QUARTERS_NARROW: [&str; 4] = ["1", "2", "3", "4"];
pub const QUARTERS_SA_WIDE: [&str; 4] = ["1st quarter", "2nd quarter", "3rd quarter", "4th quarter"];
pub const QUARTERS_SA_ABBR: [&str; 4] = ["Q1", "Q2", "Q3", "Q4"];
pub const QUARTERS_SA_NARROW: [&str; 4] = ["1", "2", "3", "4"];

/// Eras indexed by CLDR era number: 0 = BC, 1 = AD.
pub const ERAS_WIDE: [&str; 2] = ["Before Christ", "Anno Domini"];
pub const ERAS_ABBR: [&str; 2] = ["BC", "AD"];
pub const ERAS_NARROW: [&str; 2] = ["B", "A"];

/// Day-period names, `(key, wide, abbreviated, narrow)`. `am`/`pm` are the
/// fixed pair a `h`/`K` pattern's `a` field prints; the rest are the FLEXIBLE
/// periods `B` prints, selected by `DAY_PERIOD_RULES`.
pub const DAY_PERIODS: &[(&str, &str, &str, &str)] = &[
    ("midnight", "midnight", "midnight", "mi"),
    ("am", "AM", "AM", "a"),
    ("noon", "noon", "noon", "n"),
    ("pm", "PM", "PM", "p"),
    ("morning1", "in the morning", "in the morning", "in the morning"),
    ("afternoon1", "in the afternoon", "in the afternoon", "in the afternoon"),
    ("evening1", "in the evening", "in the evening", "in the evening"),
    ("night1", "at night", "at night", "at night"),
];

/// UTS #35 §4.7 flexible day-period rules for `en` (supplemental/dayPeriods.json).
/// `(key, at, from, before)` in minutes past local midnight; `at` is -1 for a
/// range rule, and `from`/`before` are -1 for an instant rule. `at` rules win.
pub const DAY_PERIOD_RULES: &[(&str, i32, i32, i32)] = &[
    ("afternoon1", -1, 720, 1080),
    ("evening1", -1, 1080, 1260),
    ("midnight", 0, -1, -1),
    ("morning1", -1, 0, 720),
    ("night1", -1, 1260, 1440),
    ("noon", 720, -1, -1),
];

// ── date/time patterns, indexed [full, long, medium, short]
pub const DATE_FORMATS: [&str; 4] = ["EEEE, MMMM d, y", "MMMM d, y", "MMM d, y", "M/d/yy"];
pub const TIME_FORMATS: [&str; 4] = ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"];
/// The `{1} … {0}` glue joining a date pattern to a time pattern.
pub const DATETIME_GLUE: [&str; 4] = ["{1}, {0}", "{1}, {0}", "{1}, {0}", "{1}, {0}"];
/// The `atTime` glue CLDR 42+ uses when a dateStyle/timeStyle pair is joined
/// (`"{1} 'at' {0}"` for full/long in `en`); ICU picks this over the plain
/// glue for dateStyle+timeStyle, which is why `timedatestyle-en.js` accepts
/// both spellings.
pub const DATETIME_GLUE_AT: [&str; 4] = ["{1} 'at' {0}", "{1} 'at' {0}", "{1}, {0}", "{1}, {0}"];

/// `availableFormats`: skeleton → pattern. The skeleton is the canonical field
/// set a request is matched against (UTS #35 §4.5 "Matching Skeletons").
pub const AVAILABLE_FORMATS: &[(&str, &str)] = &[
    ("Bh", "h B"),
    ("Bhm", "h:mm B"),
    ("Bhms", "h:mm:ss B"),
    ("E", "ccc"),
    ("EBhm", "E h:mm B"),
    ("EBhms", "E h:mm:ss B"),
    ("EHm", "E HH:mm"),
    ("EHms", "E HH:mm:ss"),
    ("Ed", "d E"),
    ("Ehm", "E h:mm a"),
    ("Ehms", "E h:mm:ss a"),
    ("Gy", "y G"),
    ("GyMMM", "MMM y G"),
    ("GyMMMEd", "E, MMM d, y G"),
    ("GyMMMd", "MMM d, y G"),
    ("GyMd", "M/d/y G"),
    ("H", "HH"),
    ("Hm", "HH:mm"),
    ("Hms", "HH:mm:ss"),
    ("Hmsv", "HH:mm:ss v"),
    ("Hmv", "HH:mm v"),
    ("M", "L"),
    ("MEd", "E, M/d"),
    ("MMM", "LLL"),
    ("MMMEd", "E, MMM d"),
    ("MMMMW-count-one", "'week' W 'of' MMMM"),
    ("MMMMW-count-other", "'week' W 'of' MMMM"),
    ("MMMMd", "MMMM d"),
    ("MMMd", "MMM d"),
    ("Md", "M/d"),
    ("d", "d"),
    ("h", "h a"),
    ("hm", "h:mm a"),
    ("hms", "h:mm:ss a"),
    ("hmsv", "h:mm:ss a v"),
    ("hmv", "h:mm a v"),
    ("ms", "mm:ss"),
    ("y", "y"),
    ("yM", "M/y"),
    ("yMEd", "E, M/d/y"),
    ("yMMM", "MMM y"),
    ("yMMMEd", "E, MMM d, y"),
    ("yMMMM", "MMMM y"),
    ("yMMMd", "MMM d, y"),
    ("yMd", "M/d/y"),
    ("yQQQ", "QQQ y"),
    ("yQQQQ", "QQQQ y"),
    ("yw-count-one", "'week' w 'of' Y"),
    ("yw-count-other", "'week' w 'of' Y"),
];

/// `appendItems`: how a requested field that the matched pattern does not
/// carry is attached to it — `(field letter, glue, field display name)`.
/// `{0}` is the pattern so far, `{1}` the new field, `{2}` its name, so
/// `{year, day}` in `en` prints "1886 (day: 1)".
pub const APPEND_ITEMS: &[(&str, &str, &str)] = &[
    ("G", "{0} {1}", "era"),
    ("y", "{0} {1}", "year"),
    ("Q", "{0} ({2}: {1})", "quarter"),
    ("M", "{0} ({2}: {1})", "month"),
    ("w", "{0} ({2}: {1})", "week"),
    ("d", "{0} ({2}: {1})", "day"),
    ("E", "{0} {1}", "day of the week"),
    ("h", "{0} ({2}: {1})", "hour"),
    ("m", "{0} ({2}: {1})", "minute"),
    ("s", "{0} ({2}: {1})", "second"),
    ("z", "{0} {1}", "time zone"),
];

/// `intervalFormats`: (skeleton, greatest-difference field, pattern). The
/// pattern names each field twice, once per endpoint.
pub const INTERVAL_FORMATS: &[(&str, &str, &str)] = &[
    ("Bh", "B", "h B – h B"),
    ("Bh", "h", "h – h B"),
    ("Bhm", "B", "h:mm B – h:mm B"),
    ("Bhm", "h", "h:mm – h:mm B"),
    ("Bhm", "m", "h:mm – h:mm B"),
    ("Gy", "G", "y G – y G"),
    ("Gy", "y", "y – y G"),
    ("GyM", "G", "M/y G – M/y G"),
    ("GyM", "M", "M/y – M/y G"),
    ("GyM", "y", "M/y – M/y G"),
    ("GyMEd", "G", "E, M/d/y G – E, M/d/y G"),
    ("GyMEd", "M", "E, M/d/y – E, M/d/y G"),
    ("GyMEd", "d", "E, M/d/y – E, M/d/y G"),
    ("GyMEd", "y", "E, M/d/y – E, M/d/y G"),
    ("GyMMM", "G", "MMM y G – MMM y G"),
    ("GyMMM", "M", "MMM – MMM y G"),
    ("GyMMM", "y", "MMM y – MMM y G"),
    ("GyMMMEd", "G", "E, MMM d, y G – E, MMM d, y G"),
    ("GyMMMEd", "M", "E, MMM d – E, MMM d, y G"),
    ("GyMMMEd", "d", "E, MMM d – E, MMM d, y G"),
    ("GyMMMEd", "y", "E, MMM d, y – E, MMM d, y G"),
    ("GyMMMd", "G", "MMM d, y G – MMM d, y G"),
    ("GyMMMd", "M", "MMM d – MMM d, y G"),
    ("GyMMMd", "d", "MMM d – d, y G"),
    ("GyMMMd", "y", "MMM d, y – MMM d, y G"),
    ("GyMd", "G", "M/d/y G – M/d/y G"),
    ("GyMd", "M", "M/d/y – M/d/y G"),
    ("GyMd", "d", "M/d/y – M/d/y G"),
    ("GyMd", "y", "M/d/y – M/d/y G"),
    ("H", "H", "HH – HH"),
    ("Hm", "H", "HH:mm – HH:mm"),
    ("Hm", "m", "HH:mm – HH:mm"),
    ("Hmv", "H", "HH:mm – HH:mm v"),
    ("Hmv", "m", "HH:mm – HH:mm v"),
    ("Hv", "H", "HH – HH v"),
    ("M", "M", "M – M"),
    ("MEd", "M", "E, M/d – E, M/d"),
    ("MEd", "d", "E, M/d – E, M/d"),
    ("MMM", "M", "MMM – MMM"),
    ("MMMEd", "M", "E, MMM d – E, MMM d"),
    ("MMMEd", "d", "E, MMM d – E, MMM d"),
    ("MMMd", "M", "MMM d – MMM d"),
    ("MMMd", "d", "MMM d – d"),
    ("Md", "M", "M/d – M/d"),
    ("Md", "d", "M/d – M/d"),
    ("d", "d", "d – d"),
    ("h", "a", "h a – h a"),
    ("h", "h", "h – h a"),
    ("hm", "a", "h:mm a – h:mm a"),
    ("hm", "h", "h:mm – h:mm a"),
    ("hm", "m", "h:mm – h:mm a"),
    ("hmv", "a", "h:mm a – h:mm a v"),
    ("hmv", "h", "h:mm – h:mm a v"),
    ("hmv", "m", "h:mm – h:mm a v"),
    ("hv", "a", "h a – h a v"),
    ("hv", "h", "h – h a v"),
    ("y", "y", "y – y"),
    ("yM", "M", "M/y – M/y"),
    ("yM", "y", "M/y – M/y"),
    ("yMEd", "M", "E, M/d/y – E, M/d/y"),
    ("yMEd", "d", "E, M/d/y – E, M/d/y"),
    ("yMEd", "y", "E, M/d/y – E, M/d/y"),
    ("yMMM", "M", "MMM – MMM y"),
    ("yMMM", "y", "MMM y – MMM y"),
    ("yMMMEd", "M", "E, MMM d – E, MMM d, y"),
    ("yMMMEd", "d", "E, MMM d – E, MMM d, y"),
    ("yMMMEd", "y", "E, MMM d, y – E, MMM d, y"),
    ("yMMMM", "M", "MMMM – MMMM y"),
    ("yMMMM", "y", "MMMM y – MMMM y"),
    ("yMMMd", "M", "MMM d – MMM d, y"),
    ("yMMMd", "d", "MMM d – d, y"),
    ("yMMMd", "y", "MMM d, y – MMM d, y"),
    ("yMd", "M", "M/d/y – M/d/y"),
    ("yMd", "d", "M/d/y – M/d/y"),
    ("yMd", "y", "M/d/y – M/d/y"),
];
/// Used when no interval pattern matches: format both endpoints and join.
pub const INTERVAL_FALLBACK: &str = "{0} – {1}";

/// ListFormat patterns: `(type, style, two, start, middle, end)`.
pub const LIST_PATTERNS: &[(&str, &str, &str, &str, &str, &str)] = &[
    ("conjunction", "long", "{0} and {1}", "{0}, {1}", "{0}, {1}", "{0}, and {1}"),
    ("conjunction", "short", "{0} & {1}", "{0}, {1}", "{0}, {1}", "{0}, & {1}"),
    ("conjunction", "narrow", "{0}, {1}", "{0}, {1}", "{0}, {1}", "{0}, {1}"),
    ("disjunction", "long", "{0} or {1}", "{0}, {1}", "{0}, {1}", "{0}, or {1}"),
    ("disjunction", "short", "{0} or {1}", "{0}, {1}", "{0}, {1}", "{0}, or {1}"),
    ("disjunction", "narrow", "{0} or {1}", "{0}, {1}", "{0}, {1}", "{0}, or {1}"),
    ("unit", "long", "{0}, {1}", "{0}, {1}", "{0}, {1}", "{0}, {1}"),
    ("unit", "short", "{0}, {1}", "{0}, {1}", "{0}, {1}", "{0}, {1}"),
    ("unit", "narrow", "{0} {1}", "{0} {1}", "{0} {1}", "{0} {1}"),
];

/// `Intl.DisplayNames` calendar names, keyed by the BCP-47 calendar id.
pub const CALENDAR_NAMES: &[(&str, &str)] = &[
    ("buddhist", "Buddhist Calendar"),
    ("chinese", "Chinese Calendar"),
    ("coptic", "Coptic Calendar"),
    ("dangi", "Dangi Calendar"),
    ("ethiopic", "Ethiopic Calendar"),
    ("ethiopic-amete-alem", "Ethiopic Amete Alem Calendar"),
    ("gregory", "Gregorian Calendar"),
    ("hebrew", "Hebrew Calendar"),
    ("indian", "Indian National Calendar"),
    ("islamic", "Hijri Calendar"),
    ("islamic-civil", "Hijri Calendar (tabular, civil epoch)"),
    ("islamic-rgsa", "Hijri Calendar (Saudi Arabia, sighting)"),
    ("islamic-tbla", "Hijri Calendar (tabular, astronomical epoch)"),
    ("islamic-umalqura", "Hijri Calendar (Umm al-Qura)"),
    ("iso8601", "ISO-8601 Calendar"),
    ("japanese", "Japanese Calendar"),
    ("persian", "Persian Calendar"),
    ("roc", "Minguo Calendar"),
];

/// RelativeTimeFormat patterns (dateFields.json), one row per unit × style:
/// `(unit, style, future_one, future_other, past_one, past_other)`.
pub const RELATIVE_PATTERNS: &[(&str, &str, &str, &str, &str, &str)] = &[
    ("second", "long", "in {0} second", "in {0} seconds", "{0} second ago", "{0} seconds ago"),
    ("second", "short", "in {0} sec.", "in {0} sec.", "{0} sec. ago", "{0} sec. ago"),
    ("second", "narrow", "in {0}s", "in {0}s", "{0}s ago", "{0}s ago"),
    ("minute", "long", "in {0} minute", "in {0} minutes", "{0} minute ago", "{0} minutes ago"),
    ("minute", "short", "in {0} min.", "in {0} min.", "{0} min. ago", "{0} min. ago"),
    ("minute", "narrow", "in {0}m", "in {0}m", "{0}m ago", "{0}m ago"),
    ("hour", "long", "in {0} hour", "in {0} hours", "{0} hour ago", "{0} hours ago"),
    ("hour", "short", "in {0} hr.", "in {0} hr.", "{0} hr. ago", "{0} hr. ago"),
    ("hour", "narrow", "in {0}h", "in {0}h", "{0}h ago", "{0}h ago"),
    ("day", "long", "in {0} day", "in {0} days", "{0} day ago", "{0} days ago"),
    ("day", "short", "in {0} day", "in {0} days", "{0} day ago", "{0} days ago"),
    ("day", "narrow", "in {0}d", "in {0}d", "{0}d ago", "{0}d ago"),
    ("week", "long", "in {0} week", "in {0} weeks", "{0} week ago", "{0} weeks ago"),
    ("week", "short", "in {0} wk.", "in {0} wk.", "{0} wk. ago", "{0} wk. ago"),
    ("week", "narrow", "in {0}w", "in {0}w", "{0}w ago", "{0}w ago"),
    ("month", "long", "in {0} month", "in {0} months", "{0} month ago", "{0} months ago"),
    ("month", "short", "in {0} mo.", "in {0} mo.", "{0} mo. ago", "{0} mo. ago"),
    ("month", "narrow", "in {0}mo", "in {0}mo", "{0}mo ago", "{0}mo ago"),
    ("quarter", "long", "in {0} quarter", "in {0} quarters", "{0} quarter ago", "{0} quarters ago"),
    ("quarter", "short", "in {0} qtr.", "in {0} qtrs.", "{0} qtr. ago", "{0} qtrs. ago"),
    ("quarter", "narrow", "in {0}q", "in {0}q", "{0}q ago", "{0}q ago"),
    ("year", "long", "in {0} year", "in {0} years", "{0} year ago", "{0} years ago"),
    ("year", "short", "in {0} yr.", "in {0} yr.", "{0} yr. ago", "{0} yr. ago"),
    ("year", "narrow", "in {0}y", "in {0}y", "{0}y ago", "{0}y ago"),
];

/// The `numeric: "auto"` literals — CLDR `relative-type-<n>`, e.g. "yesterday",
/// "now", "next quarter". `(unit, style, offset, text)`; a unit/offset absent
/// here has no idiomatic form and falls back to the numeric pattern.
pub const RELATIVE_LITERALS: &[(&str, &str, i32, &str)] = &[
    ("second", "long", 0, "now"),
    ("second", "short", 0, "now"),
    ("second", "narrow", 0, "now"),
    ("minute", "long", 0, "this minute"),
    ("minute", "short", 0, "this minute"),
    ("minute", "narrow", 0, "this minute"),
    ("hour", "long", 0, "this hour"),
    ("hour", "short", 0, "this hour"),
    ("hour", "narrow", 0, "this hour"),
    ("day", "long", -1, "yesterday"),
    ("day", "long", 0, "today"),
    ("day", "long", 1, "tomorrow"),
    ("day", "short", -1, "yesterday"),
    ("day", "short", 0, "today"),
    ("day", "short", 1, "tomorrow"),
    ("day", "narrow", -1, "yesterday"),
    ("day", "narrow", 0, "today"),
    ("day", "narrow", 1, "tomorrow"),
    ("week", "long", -1, "last week"),
    ("week", "long", 0, "this week"),
    ("week", "long", 1, "next week"),
    ("week", "short", -1, "last wk."),
    ("week", "short", 0, "this wk."),
    ("week", "short", 1, "next wk."),
    ("week", "narrow", -1, "last wk."),
    ("week", "narrow", 0, "this wk."),
    ("week", "narrow", 1, "next wk."),
    ("month", "long", -1, "last month"),
    ("month", "long", 0, "this month"),
    ("month", "long", 1, "next month"),
    ("month", "short", -1, "last mo."),
    ("month", "short", 0, "this mo."),
    ("month", "short", 1, "next mo."),
    ("month", "narrow", -1, "last mo."),
    ("month", "narrow", 0, "this mo."),
    ("month", "narrow", 1, "next mo."),
    ("quarter", "long", -1, "last quarter"),
    ("quarter", "long", 0, "this quarter"),
    ("quarter", "long", 1, "next quarter"),
    ("quarter", "short", -1, "last qtr."),
    ("quarter", "short", 0, "this qtr."),
    ("quarter", "short", 1, "next qtr."),
    ("quarter", "narrow", -1, "last qtr."),
    ("quarter", "narrow", 0, "this qtr."),
    ("quarter", "narrow", 1, "next qtr."),
    ("year", "long", -1, "last year"),
    ("year", "long", 0, "this year"),
    ("year", "long", 1, "next year"),
    ("year", "short", -1, "last yr."),
    ("year", "short", 0, "this yr."),
    ("year", "short", 1, "next yr."),
    ("year", "narrow", -1, "last yr."),
    ("year", "narrow", 0, "this yr."),
    ("year", "narrow", 1, "next yr."),
];

// ── number symbols and patterns (numbers.json, numberSystem=latn)
pub const SYM_DECIMAL: &str = ".";
pub const SYM_GROUP: &str = ",";
pub const SYM_PERCENT_SIGN: &str = "%";
pub const SYM_PLUS_SIGN: &str = "+";
pub const SYM_MINUS_SIGN: &str = "-";
pub const SYM_APPROX_SIGN: &str = "~";
pub const SYM_EXPONENTIAL: &str = "E";
pub const SYM_NAN: &str = "NaN";
pub const SYM_INFINITY: &str = "∞";
pub const PATTERN_DECIMAL: &str = "#,##0.###";
pub const PATTERN_PERCENT: &str = "#,##0%";
pub const PATTERN_CURRENCY: &str = "¤#,##0.00";
/// `signDisplay` and the currencySign:"accounting" pattern share this row: its
/// negative subpattern is what wraps a negative amount in parentheses.
pub const PATTERN_ACCOUNTING: &str = "¤#,##0.00;(¤#,##0.00)";
/// `formatRange`'s joiner and `approximatelySign`'s wrapper.
pub const PATTERN_RANGE: &str = "{0}–{1}";
pub const PATTERN_APPROX: &str = "~{0}";

/// Compact decimal patterns: `(power of ten, plural count, pattern)`. The count
/// of `0`s in the pattern is the number of integer digits it keeps.
pub const COMPACT_DECIMAL_SHORT: &[(u32, &str, &str)] = &[
    (3, "one", "0K"),
    (3, "other", "0K"),
    (4, "one", "00K"),
    (4, "other", "00K"),
    (5, "one", "000K"),
    (5, "other", "000K"),
    (6, "one", "0M"),
    (6, "other", "0M"),
    (7, "one", "00M"),
    (7, "other", "00M"),
    (8, "one", "000M"),
    (8, "other", "000M"),
    (9, "one", "0B"),
    (9, "other", "0B"),
    (10, "one", "00B"),
    (10, "other", "00B"),
    (11, "one", "000B"),
    (11, "other", "000B"),
    (12, "one", "0T"),
    (12, "other", "0T"),
    (13, "one", "00T"),
    (13, "other", "00T"),
    (14, "one", "000T"),
    (14, "other", "000T"),
];
pub const COMPACT_DECIMAL_LONG: &[(u32, &str, &str)] = &[
    (3, "one", "0 thousand"),
    (3, "other", "0 thousand"),
    (4, "one", "00 thousand"),
    (4, "other", "00 thousand"),
    (5, "one", "000 thousand"),
    (5, "other", "000 thousand"),
    (6, "one", "0 million"),
    (6, "other", "0 million"),
    (7, "one", "00 million"),
    (7, "other", "00 million"),
    (8, "one", "000 million"),
    (8, "other", "000 million"),
    (9, "one", "0 billion"),
    (9, "other", "0 billion"),
    (10, "one", "00 billion"),
    (10, "other", "00 billion"),
    (11, "one", "000 billion"),
    (11, "other", "000 billion"),
    (12, "one", "0 trillion"),
    (12, "other", "0 trillion"),
    (13, "one", "00 trillion"),
    (13, "other", "00 trillion"),
    (14, "one", "000 trillion"),
    (14, "other", "000 trillion"),
];

/// Unit display patterns for the 45 sanctioned units of ECMA-402 Table 2,
/// `(unit, width, one, other)`. `{0}` is the formatted number.
pub const UNIT_PATTERNS: &[(&str, &str, &str, &str)] = &[
    ("acre", "long", "{0} acre", "{0} acres"),
    ("acre", "short", "{0} ac", "{0} ac"),
    ("acre", "narrow", "{0}ac", "{0}ac"),
    ("bit", "long", "{0} bit", "{0} bits"),
    ("bit", "short", "{0} bit", "{0} bit"),
    ("bit", "narrow", "{0}bit", "{0}bit"),
    ("byte", "long", "{0} byte", "{0} bytes"),
    ("byte", "short", "{0} byte", "{0} byte"),
    ("byte", "narrow", "{0}B", "{0}B"),
    ("celsius", "long", "{0} degree Celsius", "{0} degrees Celsius"),
    ("celsius", "short", "{0}°C", "{0}°C"),
    ("celsius", "narrow", "{0}°C", "{0}°C"),
    ("centimeter", "long", "{0} centimeter", "{0} centimeters"),
    ("centimeter", "short", "{0} cm", "{0} cm"),
    ("centimeter", "narrow", "{0}cm", "{0}cm"),
    ("day", "long", "{0} day", "{0} days"),
    ("day", "short", "{0} day", "{0} days"),
    ("day", "narrow", "{0}d", "{0}d"),
    ("degree", "long", "{0} degree", "{0} degrees"),
    ("degree", "short", "{0} deg", "{0} deg"),
    ("degree", "narrow", "{0}°", "{0}°"),
    ("fahrenheit", "long", "{0} degree Fahrenheit", "{0} degrees Fahrenheit"),
    ("fahrenheit", "short", "{0}°F", "{0}°F"),
    ("fahrenheit", "narrow", "{0}°", "{0}°"),
    ("fluid-ounce", "long", "{0} fluid ounce", "{0} fluid ounces"),
    ("fluid-ounce", "short", "{0} fl oz", "{0} fl oz"),
    ("fluid-ounce", "narrow", "{0}fl oz", "{0}fl oz"),
    ("foot", "long", "{0} foot", "{0} feet"),
    ("foot", "short", "{0} ft", "{0} ft"),
    ("foot", "narrow", "{0}′", "{0}′"),
    ("gallon", "long", "{0} gallon", "{0} gallons"),
    ("gallon", "short", "{0} gal", "{0} gal"),
    ("gallon", "narrow", "{0}gal", "{0}gal"),
    ("gigabit", "long", "{0} gigabit", "{0} gigabits"),
    ("gigabit", "short", "{0} Gb", "{0} Gb"),
    ("gigabit", "narrow", "{0}Gb", "{0}Gb"),
    ("gigabyte", "long", "{0} gigabyte", "{0} gigabytes"),
    ("gigabyte", "short", "{0} GB", "{0} GB"),
    ("gigabyte", "narrow", "{0}GB", "{0}GB"),
    ("gram", "long", "{0} gram", "{0} grams"),
    ("gram", "short", "{0} g", "{0} g"),
    ("gram", "narrow", "{0}g", "{0}g"),
    ("hectare", "long", "{0} hectare", "{0} hectares"),
    ("hectare", "short", "{0} ha", "{0} ha"),
    ("hectare", "narrow", "{0}ha", "{0}ha"),
    ("hour", "long", "{0} hour", "{0} hours"),
    ("hour", "short", "{0} hr", "{0} hr"),
    ("hour", "narrow", "{0}h", "{0}h"),
    ("inch", "long", "{0} inch", "{0} inches"),
    ("inch", "short", "{0} in", "{0} in"),
    ("inch", "narrow", "{0}″", "{0}″"),
    ("kilobit", "long", "{0} kilobit", "{0} kilobits"),
    ("kilobit", "short", "{0} kb", "{0} kb"),
    ("kilobit", "narrow", "{0}kb", "{0}kb"),
    ("kilobyte", "long", "{0} kilobyte", "{0} kilobytes"),
    ("kilobyte", "short", "{0} kB", "{0} kB"),
    ("kilobyte", "narrow", "{0}kB", "{0}kB"),
    ("kilogram", "long", "{0} kilogram", "{0} kilograms"),
    ("kilogram", "short", "{0} kg", "{0} kg"),
    ("kilogram", "narrow", "{0}kg", "{0}kg"),
    ("kilometer", "long", "{0} kilometer", "{0} kilometers"),
    ("kilometer", "short", "{0} km", "{0} km"),
    ("kilometer", "narrow", "{0}km", "{0}km"),
    ("liter", "long", "{0} liter", "{0} liters"),
    ("liter", "short", "{0} L", "{0} L"),
    ("liter", "narrow", "{0}L", "{0}L"),
    ("megabit", "long", "{0} megabit", "{0} megabits"),
    ("megabit", "short", "{0} Mb", "{0} Mb"),
    ("megabit", "narrow", "{0}Mb", "{0}Mb"),
    ("megabyte", "long", "{0} megabyte", "{0} megabytes"),
    ("megabyte", "short", "{0} MB", "{0} MB"),
    ("megabyte", "narrow", "{0}MB", "{0}MB"),
    ("meter", "long", "{0} meter", "{0} meters"),
    ("meter", "short", "{0} m", "{0} m"),
    ("meter", "narrow", "{0}m", "{0}m"),
    ("microsecond", "long", "{0} microsecond", "{0} microseconds"),
    ("microsecond", "short", "{0} μs", "{0} μs"),
    ("microsecond", "narrow", "{0}μs", "{0}μs"),
    ("mile", "long", "{0} mile", "{0} miles"),
    ("mile", "short", "{0} mi", "{0} mi"),
    ("mile", "narrow", "{0}mi", "{0}mi"),
    ("mile-scandinavian", "long", "{0} mile-scandinavian", "{0} miles-scandinavian"),
    ("mile-scandinavian", "short", "{0} smi", "{0} smi"),
    ("mile-scandinavian", "narrow", "{0}smi", "{0}smi"),
    ("milliliter", "long", "{0} milliliter", "{0} milliliters"),
    ("milliliter", "short", "{0} mL", "{0} mL"),
    ("milliliter", "narrow", "{0}mL", "{0}mL"),
    ("millimeter", "long", "{0} millimeter", "{0} millimeters"),
    ("millimeter", "short", "{0} mm", "{0} mm"),
    ("millimeter", "narrow", "{0}mm", "{0}mm"),
    ("millisecond", "long", "{0} millisecond", "{0} milliseconds"),
    ("millisecond", "short", "{0} ms", "{0} ms"),
    ("millisecond", "narrow", "{0}ms", "{0}ms"),
    ("minute", "long", "{0} minute", "{0} minutes"),
    ("minute", "short", "{0} min", "{0} min"),
    ("minute", "narrow", "{0}m", "{0}m"),
    ("month", "long", "{0} month", "{0} months"),
    ("month", "short", "{0} mth", "{0} mths"),
    ("month", "narrow", "{0}m", "{0}m"),
    ("nanosecond", "long", "{0} nanosecond", "{0} nanoseconds"),
    ("nanosecond", "short", "{0} ns", "{0} ns"),
    ("nanosecond", "narrow", "{0}ns", "{0}ns"),
    ("ounce", "long", "{0} ounce", "{0} ounces"),
    ("ounce", "short", "{0} oz", "{0} oz"),
    ("ounce", "narrow", "{0}oz", "{0}oz"),
    ("percent", "long", "{0} percent", "{0} percent"),
    ("percent", "short", "{0}%", "{0}%"),
    ("percent", "narrow", "{0}%", "{0}%"),
    ("petabyte", "long", "{0} petabyte", "{0} petabytes"),
    ("petabyte", "short", "{0} PB", "{0} PB"),
    ("petabyte", "narrow", "{0}PB", "{0}PB"),
    ("pound", "long", "{0} pound", "{0} pounds"),
    ("pound", "short", "{0} lb", "{0} lb"),
    ("pound", "narrow", "{0}#", "{0}#"),
    ("second", "long", "{0} second", "{0} seconds"),
    ("second", "short", "{0} sec", "{0} sec"),
    ("second", "narrow", "{0}s", "{0}s"),
    ("stone", "long", "{0} stone", "{0} stones"),
    ("stone", "short", "{0} st", "{0} st"),
    ("stone", "narrow", "{0}st", "{0}st"),
    ("terabit", "long", "{0} terabit", "{0} terabits"),
    ("terabit", "short", "{0} Tb", "{0} Tb"),
    ("terabit", "narrow", "{0}Tb", "{0}Tb"),
    ("terabyte", "long", "{0} terabyte", "{0} terabytes"),
    ("terabyte", "short", "{0} TB", "{0} TB"),
    ("terabyte", "narrow", "{0}TB", "{0}TB"),
    ("week", "long", "{0} week", "{0} weeks"),
    ("week", "short", "{0} wk", "{0} wks"),
    ("week", "narrow", "{0}w", "{0}w"),
    ("yard", "long", "{0} yard", "{0} yards"),
    ("yard", "short", "{0} yd", "{0} yd"),
    ("yard", "narrow", "{0}yd", "{0}yd"),
    ("year", "long", "{0} year", "{0} years"),
    ("year", "short", "{0} yr", "{0} yrs"),
    ("year", "narrow", "{0}y", "{0}y"),
];

/// CLDR carries idiomatic names for many `x-per-y` pairs (`km/h`, not `km/hour`);
/// where it does, ECMA-402's compound construction must not be used instead.
/// Only pairs of sanctioned units are reachable, so only those are emitted.
pub const UNIT_PER_PATTERNS: &[(&str, &str, &str, &str)] = &[
    ("kilometer-per-hour", "long", "{0} kilometer per hour", "{0} kilometers per hour"),
    ("kilometer-per-hour", "short", "{0} km/h", "{0} km/h"),
    ("kilometer-per-hour", "narrow", "{0}km/h", "{0}km/h"),
    ("liter-per-kilometer", "long", "{0} liter per kilometer", "{0} liters per kilometer"),
    ("liter-per-kilometer", "short", "{0} L/km", "{0} L/km"),
    ("liter-per-kilometer", "narrow", "{0}L/km", "{0}L/km"),
    ("meter-per-second", "long", "{0} meter per second", "{0} meters per second"),
    ("meter-per-second", "short", "{0} m/s", "{0} m/s"),
    ("meter-per-second", "narrow", "{0}m/s", "{0}m/s"),
    ("mile-per-gallon", "long", "{0} mile per gallon", "{0} miles per gallon"),
    ("mile-per-gallon", "short", "{0} mpg", "{0} mpg"),
    ("mile-per-gallon", "narrow", "{0}mpg", "{0}mpg"),
    ("mile-per-hour", "long", "{0} mile per hour", "{0} miles per hour"),
    ("mile-per-hour", "short", "{0} mph", "{0} mph"),
    ("mile-per-hour", "narrow", "{0}mph", "{0}mph"),
];

/// A DENOMINATOR's `perUnitPattern` — UTS #35 "Compound Units" step 2, used
/// when no idiomatic `x-per-y` row exists: `{0}` takes the whole formatted
/// numerator, so `byte-per-year` short is "2 byte" in "{0}/y" = "2 byte/y".
pub const UNIT_PER_UNIT: &[(&str, &str, &str)] = &[
    ("centimeter", "long", "{0} per centimeter"),
    ("centimeter", "short", "{0}/cm"),
    ("centimeter", "narrow", "{0}/cm"),
    ("day", "long", "{0} per day"),
    ("day", "short", "{0}/d"),
    ("day", "narrow", "{0}/d"),
    ("foot", "long", "{0} per foot"),
    ("foot", "short", "{0}/ft"),
    ("foot", "narrow", "{0}/ft"),
    ("gallon", "long", "{0} per gallon"),
    ("gallon", "short", "{0}/gal US"),
    ("gallon", "narrow", "{0}/gal"),
    ("gram", "long", "{0} per gram"),
    ("gram", "short", "{0}/g"),
    ("gram", "narrow", "{0}/g"),
    ("hour", "long", "{0} per hour"),
    ("hour", "short", "{0}/h"),
    ("hour", "narrow", "{0}/h"),
    ("inch", "long", "{0} per inch"),
    ("inch", "short", "{0}/in"),
    ("inch", "narrow", "{0}/in"),
    ("kilogram", "long", "{0} per kilogram"),
    ("kilogram", "short", "{0}/kg"),
    ("kilogram", "narrow", "{0}/kg"),
    ("kilometer", "long", "{0} per kilometer"),
    ("kilometer", "short", "{0}/km"),
    ("kilometer", "narrow", "{0}/km"),
    ("liter", "long", "{0} per liter"),
    ("liter", "short", "{0}/L"),
    ("liter", "narrow", "{0}/L"),
    ("meter", "long", "{0} per meter"),
    ("meter", "short", "{0}/m"),
    ("meter", "narrow", "{0}/m"),
    ("minute", "long", "{0} per minute"),
    ("minute", "short", "{0}/min"),
    ("minute", "narrow", "{0}/min"),
    ("month", "long", "{0} per month"),
    ("month", "short", "{0}/m"),
    ("month", "narrow", "{0}/m"),
    ("ounce", "long", "{0} per ounce"),
    ("ounce", "short", "{0}/oz"),
    ("ounce", "narrow", "{0}/oz"),
    ("pound", "long", "{0} per pound"),
    ("pound", "short", "{0}/lb"),
    ("pound", "narrow", "{0}/lb"),
    ("second", "long", "{0} per second"),
    ("second", "short", "{0}/s"),
    ("second", "narrow", "{0}/s"),
    ("week", "long", "{0} per week"),
    ("week", "short", "{0}/w"),
    ("week", "narrow", "{0}/w"),
    ("year", "long", "{0} per year"),
    ("year", "short", "{0}/y"),
    ("year", "narrow", "{0}/y"),
];

/// `compoundUnitPattern`: the last-resort numerator/denominator join when the
/// denominator has no `perUnitPattern` either. Indexed long/short/narrow.
pub const UNIT_COMPOUND_PER: [&str; 3] = ["{0} per {1}", "{0}/{1}", "{0}/{1}"];

