pub const SNIPPETS: &[&str] = &[
    // Unexpected tokens and bad statements.
    "x = = 1\n",
    "x = \n",
    "print 'hello'\n",
    "a b\n",
    "1 +\n",
    "def\n",
    "def f\n",
    "def f(:\n",
    "def f():\npass\n",
    "def f():\n",
    "def f(): return\n  x\n",
    "if x\n  pass\n",
    "if x:\n",
    "if x:\npass\n",
    "if x: pass\nelse\n  pass\n",
    "while True print(1)\n",
    "for x in : pass\n",
    "for in y: pass\n",
    "for x y: pass\n",
    "class A(:\n  pass\n",
    "class A\n  pass\n",
    "x = (1, 2\n",
    "x = [1, 2\n",
    "x = {1: 2\n",
    "x = 1)\n",
    "x = 1]\n",
    "f(a b)\n",
    "f(a=1, b)\n",
    "f(**a, *b)\n",
    "f(a=1, a=2)\n",
    "f(a for a in b, c)\n",
    "f(x=)\n",
    "f(=1)\n",
    "f(a.b=1)\n",
    "lambda: yield\n",
    "lambda x, x: 0\n",
    "lambda *: 0\n",
    "lambda ,: 0\n",
    "def f(a, a): pass\n",
    "def f(a=1, b): pass\n",
    "def f(*): pass\n",
    "def f(*, =1): pass\n",
    "def f(*,): pass\n",
    "def f(a=1, b, *): pass\n",
    "lambda a=1, b, *: 0\n",
    "lambda *, : 0\n",
    "def f(*, **k): pass\n",
    "def f(**k, a): pass\n",
    "def f(/): pass\n",
    "def f(a, /, b, /): pass\n",
    "def f(,): pass\n",
    "def f(a, *a): pass\n",
    "def f(a=1, /, b): pass\n",
    "def f(*a, *b): pass\n",
    "def f() -> : pass\n",
    "def f(a, a) x: pass\n",
    "async x\n",
    "async def f(): await\n",
    "await await x\n",
    "x := 1\n",
    "(x := 1) = 2\n",
    "[x := 1, y]\n",
    "f(x := 1 = 2)\n",
    "(*a)\n",
    "(**a)\n",
    "print(*a for a in b)\n",
    "{*a: 1}\n",
    "{a: *b}\n",
    "{**a for a in b}\n",
    "{*a for a in b}\n",
    "{a: b, c}\n",
    "{a, b: c}\n",
    "[*a for a in b]\n",
    "(*a for a in b)\n",
    "a[1:*b]\n",
    "a[x:=1:2]\n",
    "a[]\n",
    "a.1\n",
    "a.\n",
    "del\n",
    "del a if b else c\n",
    "del not a\n",
    "import\n",
    "import a,\n",
    "import a.\n",
    "from import x\n",
    "from a import\n",
    "from a import b,\n",
    "from a import ()\n",
    "from . import (a, b,)\n",
    "from .. import *\n",
    "global\n",
    "global a,\n",
    "assert\n",
    "raise from x\n",
    "return *a, b\n",
    "yield = 1\n",
    "x = yield = 1\n",
    "x: int = 1 = 2\n",
    "x, y: int\n",
    "*a: int\n",
    "a, b += 1\n",
    "a + 1 = 2\n",
    "f() = 1\n",
    "x if y\n",
    "x if y else\n",
    "a if b if c else d else e\n",
    "a or lambda: b\n",
    "not lambda: x\n",
    "a == not b\n",
    "a not b\n",
    "a is not not b\n",
    "a < b < c\n",
    "-not a\n",
    "a ** -b ** c\n",
    "[x for x in y if a else b]\n",
    "[x for x in lambda: y]\n",
    "[x if c for x in y]\n",
    "[x async for x in y]\n",
    "[x for x, in y]\n",
    "[x for x, not in y]\n",
    "try:\n  pass\n",
    "try:\n  pass\nexcept A, B:\n  pass\n",
    "try:\n  pass\nexcept* A:\n  pass\nexcept B:\n  pass\n",
    "try:\n  pass\nexcept A:\n  pass\nexcept* B:\n  pass\n",
    "try:\n  pass\nexcept*:\n  pass\n",
    "try:\n  pass\nelse:\n  pass\n",
    "try:\n  pass\nfinally:\n  pass\nexcept:\n  pass\n",
    "with a, : pass\n",
    "with (a, b) as c: pass\n",
    "with (a as b) + c: pass\n",
    "with (a, *b) as c: pass\n",
    "with (a, *b): pass\n",
    "with (yield x): pass\n",
    "with (): pass\n",
    "with (a as b, c as d,): pass\n",
    "with (a, b), c: pass\n",
    "with (a) c: pass\n",
    "with (a, f(x=1, x=2)): pass\n",
    "with (a as b c): pass\n",
    "with (a := b): pass\n",
    "with (x for x in y): pass\n",
    "with a as b, (c as d): pass\n",
    "@\ndef f(): pass\n",
    "@d\nx = 1\n",
    "@d\nasync with x: pass\n",
    "@d def f(): pass\n",
    "class A(x=1, x=2): pass\n",
    "class A[]: pass\n",
    "def f[T,](): pass\n",
    "def f[*T: int](): pass\n",
    "type X = \n",
    "type X[T] = list[T]\n",
    "type = 1\n",
    "type X\n",
    "match x:\n  case 1:\n    pass\n",
    "match x:\ncase 1: pass\n",
    "match x:\n  pass\n",
    "match x:\n  case 1 + 2 + 3: pass\n",
    "match x:\n  case -x: pass\n",
    "match x:\n  case 1 - x: pass\n",
    "match x:\n  case a as _: pass\n",
    "match x:\n  case {a: 1}: pass\n",
    "match x:\n  case {**r, 'a': 1}: pass\n",
    "match x:\n  case {, }: pass\n",
    "match x:\n  case C(a=1, b): pass\n",
    "match x:\n  case C(a=1, 2): pass\n",
    "match x:\n  case (a b): pass\n",
    "match x:\n  case [,]: pass\n",
    "match x:\n  case *a | b: pass\n",
    "match x, :\n  case a: pass\n",
    "match x,, :\n  case a: pass\n",
    "match x, y:\n  case a, b if a: pass\n  case _: pass\n",
    "match x:\n  case a.b.c(d, e=f): pass\n  case {1: a, 'b': c, **d}: pass\n  case [a, *_]: pass\n",
    "match x:\n  case (a): pass\n  case (): pass\n  case (a,): pass\n  case (a, b,): pass\n",
    "match x:\n  case None | True | False | -1 | 1.5 | 2j | -1 + 2j | 'a' 'b': pass\n",
    "match x:\n  case b'a' 'b': pass\n",
    "match x:\n  case b'a' 'b' x: pass\n",
    "match x:\n  case {b'a' 'b': 1}: pass\n",
    "match x:\n  case {b'a' 'b' 1}: pass\n",
    "match x:\n  case a as _ b: pass\n",
    "match x:\n  case (a as _): pass\n",
    "with b'a' 'b': pass\n",
    "with b'a' 'b'\n",
    "with (*a)\n",
    "with (**a): pass\n",
    "with (*a) as b: pass\n",
    "f'{a!x}' except\n",
    "(*a) as b\n",
    "(**a)\n",
    "def f(a, a) x: pass\n",
    "def f(a, a) -> x: pass\n",
    "lambda a, a: 0 except\n",
    "  x = 1\n",
    "x = 1\n    y = 2\n",
    "if x:\n    a\n  b\n",
    "if x:\n\ta\n        b\n",
    "x = 'unterminated\n",
    "x = \"\"\"never closed\n",
    "x = 1 $ 2\n",
    "x = 0x\n",
    "x = 1_\n",
    "f'{'\n",
    "f'{a!x}'\n",
    "f'{*a}'\n",
    "f'{a b}'\n",
    "f'{}'\n",
    "f'{a:{b:{c}}}'\n",
    "f'{x=}' f'{y!r:>10}'\n",
    "f'{lambda: 1}'\n",
    "f'{yield}'\n",
    "f'{(x := 1)}'\n",
    "'\\N{NOT A REAL NAME}'\n",
    "x = (\n",
    "x = [1,\n  2,\n",
    "(",
    ")",
    "@",
    "",
    "\n\n\n",
    "pass;;\n",
    "pass; pass;\n",
    "a = b = c = d\n",
    "x = *a, *b\n",
    "for *a, b in c: pass\n",
    "print(a, *b, c=1, **d, e=2)\n",
    "def f(a, /, b=1, *c, d, e=2, **f): pass\n",
    "def f(**): pass\n",
    "def f(a, **): pass\n",
    "def f(*, a): pass\n",
    "lambda a, /, b=1, *c, d, **e: 0\n",
    "x[1:2, ::3, ...]\n",
    "x[a, b:c, *d]\n",
    "x[1,]\n",
    "(yield)\n",
    "(a, *b, c)\n",
    "a if b else lambda: c if d else e\n",
    "not not a == b and c or d\n",
    "a @ b @= c\n",
    "global a, b\nnonlocal c\n",
    "if a:\n  pass\nelif b:\n  pass\nelif c:\n  pass\nelse:\n  pass\n",
    "async def f():\n  async with a as b, c: pass\n  async for x in y: pass\n  await z\n",
    "class A[T: int, *Ts, **P](B, metaclass=M): pass\n",
    "x = (a for b in c for d in e if f if g)\n",
    "print(f'{a}' 'b' f'{c!r:>{d}}')\n",
    "b'a' b'b'\n",
    "b'a' 'b'\n",
    "u'a' 'b'\n",
    "x = 1 if True else 2, 3\n",
    "match = 1\ncase = 2\ntype = 3\nprint(match, case, type)\n",
    "match(x)\n",
    "match x:\n  case _:\n    pass\nmatch = 3\n",
    "type X[T: (int, str)] = dict[str, T]\n",
    "lambda: (yield)\n",
    "x = {**a, 'b': 1, **c}\n",
    "x = {1, 2, *a}\n",
    "(a := 1, b := 2)\n",
    "a[b := 1]\n",
    "f(a := 1)\n",
    "while (x := f()): pass\n",
    "if (a := 1) and (b := 2): pass\n",
    "assert x, 'msg'\n",
    "raise E from None\n",
    "del a, b[1], c.d, (e, f), [g]\n",
    "with a as (b, c), d as [e]: pass\n",
    "try:\n  pass\nexcept* (A, B) as e:\n  pass\nelse:\n  pass\nfinally:\n  pass\n",
    "for x in 1, 2, 3: pass\n",
    "return\n",
    "x = yield from y\n",
    "x = yield a, b\n",
    "def f(): yield\n",
    "a = 1; b = 2\n",
    "x = (\n  1 +\n  2\n)\n",
    "if True:\n  pass\n\n\n  # comment\n  pass\n",
    "x = \\\n  1\n",
    // Comments in f-string fields (PEP 701): to the end of the line, even
    // in a single-quoted literal, and not part of `=` debugging text.
    "f\"{1+2 = # my comment\n  }\"\n",
    "f\"{x # c\"\n}\"\n",
    "f\"{(x # c\n)}\"\n",
    "f\"{x # c}\"\ny\n",
    "f\"{x # c}\n}\"\n",
    "f\"{x = # c\n}\"\n",
    "f\"{x = #c\n = }\"\n",
    "f\"{x!r # c\n}\"\n",
    "f\"{x:{y # c\n}}\"\n",
    "f'''{x # c'''\n}'''\n",
    "f\"{x # c \\\n}\"\n",
    "f\"{x #\r\n}\"\n",
    "f\"{x = # a '\n  }\"\n",
    "f\"{[x # c\n , # d\n y] = }\"\n",
    "f\"{'#' = }\"\n",
    "f\"{x:{y # c\n} = }\"\n",
];
