#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum TokenType {
    Illegal,
    Eof,
    Ident,
    Int,
    BigInt,
    Float,
    String,
    Template,
    Regex,
    Assign,
    Plus,
    Minus,
    Bang,
    Asterisk,
    Slash,
    Percent,
    LessThan,
    GreaterThan,
    LessThanOrEqual,
    GreaterThanOrEqual,
    Equal,
    NotEqual,
    StrictEqual,
    StrictNotEqual,
    And,
    Or,
    Comma,
    Semicolon,
    Colon,
    Dot,
    Spread,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Function,
    Let,
    Var,
    Const,
    True,
    False,
    If,
    Else,
    Return,
    Null,
    Undefined,
    While,
    For,
    Break,
    Continue,
    Throw,
    Try,
    Catch,
    Finally,
    Class,
    Extends,
    New,
    This,
    Super,
    Static,
    Async,
    Await,
    Of,
    In,
    Do,
    Switch,
    Case,
    Default,
    Get,
    Set,
    Typeof,
    Instanceof,
    Void,
    Delete,
    Yield,
    Import,
    Debugger,
    Arrow,
    PlusAssign,
    MinusAssign,
    MultiplyAssign,
    DivideAssign,
    Increment,
    Decrement,
    Question,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    LeftShift,
    RightShift,
    UnsignedRightShift,
    UnsignedRightShiftAssign,
    PercentAssign,
    BitwiseAndAssign,
    BitwiseOrAssign,
    BitwiseXorAssign,
    LeftShiftAssign,
    RightShiftAssign,
    Exponent,
    ExponentAssign,
    NullishCoalescing,
    OptionalChain,
    NullishAssign,
    AndAssign,
    OrAssign,
    Hash,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
    pub token_type: TokenType,
    pub literal: String,
    pub line: usize,
    pub column: usize,
    pub had_newline_before: bool,
    pub raw_literal: Option<String>,
}

impl Token {
    pub fn new(token_type: TokenType, literal: String, line: usize, column: usize) -> Self {
        Self {
            token_type,
            literal,
            line,
            column,
            had_newline_before: false,
            raw_literal: None,
        }
    }
}

pub fn lookup_ident(ident: &str) -> TokenType {
    match ident {
        "function" => TokenType::Function,
        "let" => TokenType::Let,
        "var" => TokenType::Var,
        "const" => TokenType::Const,
        "true" => TokenType::True,
        "false" => TokenType::False,
        "if" => TokenType::If,
        "else" => TokenType::Else,
        "return" => TokenType::Return,
        "null" => TokenType::Null,
        "undefined" => TokenType::Undefined,
        "while" => TokenType::While,
        "for" => TokenType::For,
        "break" => TokenType::Break,
        "continue" => TokenType::Continue,
        "throw" => TokenType::Throw,
        "try" => TokenType::Try,
        "catch" => TokenType::Catch,
        "finally" => TokenType::Finally,
        "class" => TokenType::Class,
        "extends" => TokenType::Extends,
        "new" => TokenType::New,
        "this" => TokenType::This,
        "super" => TokenType::Super,
        "static" => TokenType::Static,
        "async" => TokenType::Async,
        "await" => TokenType::Await,
        "of" => TokenType::Of,
        "in" => TokenType::In,
        "do" => TokenType::Do,
        "switch" => TokenType::Switch,
        "case" => TokenType::Case,
        "default" => TokenType::Default,
        "get" => TokenType::Get,
        "set" => TokenType::Set,
        "typeof" => TokenType::Typeof,
        "instanceof" => TokenType::Instanceof,
        "void" => TokenType::Void,
        "delete" => TokenType::Delete,
        "yield" => TokenType::Yield,
        "import" => TokenType::Import,
        "debugger" => TokenType::Debugger,
        _ => TokenType::Ident,
    }
}

pub fn default_operators() -> Vec<(&'static str, TokenType)> {
    vec![
        ("**=", TokenType::ExponentAssign),
        ("**", TokenType::Exponent),
        ("??=", TokenType::NullishAssign),
        ("??", TokenType::NullishCoalescing),
        ("?.", TokenType::OptionalChain),
        ("&&=", TokenType::AndAssign),
        ("||=", TokenType::OrAssign),
        ("+=", TokenType::PlusAssign),
        ("-=", TokenType::MinusAssign),
        ("*=", TokenType::MultiplyAssign),
        ("/=", TokenType::DivideAssign),
        ("%=", TokenType::PercentAssign),
        ("<<=", TokenType::LeftShiftAssign),
        (">>=", TokenType::RightShiftAssign),
        ("&=", TokenType::BitwiseAndAssign),
        ("|=", TokenType::BitwiseOrAssign),
        ("^=", TokenType::BitwiseXorAssign),
        ("++", TokenType::Increment),
        ("--", TokenType::Decrement),
        (">>>=", TokenType::UnsignedRightShiftAssign),
        (">>>", TokenType::UnsignedRightShift),
        ("<<", TokenType::LeftShift),
        (">>", TokenType::RightShift),
        ("<=", TokenType::LessThanOrEqual),
        (">=", TokenType::GreaterThanOrEqual),
        ("===", TokenType::StrictEqual),
        ("!==", TokenType::StrictNotEqual),
        ("==", TokenType::Equal),
        ("!=", TokenType::NotEqual),
        ("&&", TokenType::And),
        ("||", TokenType::Or),
        ("=>", TokenType::Arrow),
        ("...", TokenType::Spread),
        ("+", TokenType::Plus),
        ("-", TokenType::Minus),
        ("*", TokenType::Asterisk),
        ("/", TokenType::Slash),
        ("%", TokenType::Percent),
        ("<", TokenType::LessThan),
        (">", TokenType::GreaterThan),
        ("=", TokenType::Assign),
        (",", TokenType::Comma),
        (";", TokenType::Semicolon),
        (":", TokenType::Colon),
        ("(", TokenType::LeftParen),
        (")", TokenType::RightParen),
        ("{", TokenType::LeftBrace),
        ("}", TokenType::RightBrace),
        ("[", TokenType::LeftBracket),
        ("]", TokenType::RightBracket),
        (".", TokenType::Dot),
        ("!", TokenType::Bang),
        ("?", TokenType::Question),
        ("&", TokenType::BitwiseAnd),
        ("|", TokenType::BitwiseOr),
        ("^", TokenType::BitwiseXor),
        ("~", TokenType::BitwiseNot),
    ]
}
