//! The bundled `torch` subset: tensors, autograd, `nn`, `optim` and a
//! checkpoint round trip through the virtual filesystem, all on the
//! runtime's CPU kernels.
#![cfg(feature = "python")]
use zipp_vm::frontend::compile_python_program;

fn run(source: &str) -> Result<Vec<String>, String> {
    let source = source.to_owned();
    std::thread::Builder::new()
        .stack_size(256 << 20)
        .spawn(move || {
            let modules = vec![("main".to_owned(), source)];
            let mut compiled = compile_python_program("main", &modules, &[], &[], false)?;
            let state = compiled.state_mut();
            state.set_limits(400_000_000, None);
            state.run_init()?;
            Ok(state.take_output())
        })
        .expect("spawn")
        .join()
        .expect("test thread")
}

#[test]
fn compiled_training_matches_pytorch_gradients_and_sgd() {
    // Golden values generated by CPU PyTorch 2.11: loss, every parameter's
    // gradient and updated weight, across five sequential training steps.
    let source = format!(
        "{}\nexpected = {}\n{}",
        include_str!("fixtures/torch_training.py"),
        include_str!("fixtures/torch_training_expected.json"),
        r#"
compiled = torch.compile(train_step, training=True)
index = 0
def done(loss):
    global index
    actual = state(loss)
    assert len(actual) == len(expected[index])
    assert all(abs(a-b) < 2e-6 for a,b in zip(actual, expected[index])), str(actual)
    index += 1
for step in range(5):
    pending = compiled(inputs, targets)
    pending.submit(done)
print('training parity', index)
"#
    );
    assert_eq!(run(&source).unwrap(), ["training parity 5"]);
}

#[test]
fn conv2d_matches_pytorch_forward_gradients_and_optimizer() {
    let out = run(include_str!("fixtures/torch_conv2d.py")).unwrap();
    assert_eq!(
        out,
        [
            "conv2d case 0 passed",
            "conv2d case 1 passed",
            "conv2d case 2 passed",
            "conv2d case 3 passed",
            "conv2d optimizer passed"
        ]
    );
}

#[test]
fn conv2d_rejects_unsupported_shapes_and_options() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.ones(1, 2, 3, 3)
w = torch.ones(2, 2, 2, 2)
for action in [lambda: F.conv2d(x,w,stride=0), lambda: F.conv2d(x,w,padding=-1), lambda: F.conv2d(x,w,groups=2), lambda: F.conv2d(x,w,torch.ones(3)), lambda: nn.Conv2d(2,3,3,groups=2), lambda: nn.Conv2d(1,1,3,device='cuda'), lambda: nn.Conv2d(1,1,3,padding_mode='reflect'), lambda: F.conv2d(torch.ones(1,2,1,1),w)]:
    try:
        action()
        print('not rejected')
    except (ValueError, RuntimeError, NotImplementedError):
        print('rejected')
try:
    torch.compile(nn.Conv2d(2,2,1))(x)
except NotImplementedError:
    print('CPU only')
"#).unwrap();
    assert_eq!(&out[..8], ["rejected"; 8]);
    assert_eq!(out[8], "CPU only");
}

#[test]
fn tensors_autograd_modules_and_checkpoints() {
    let source = r#"
import torch
import torch.nn.functional as F
from torch import nn

x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x.shape, x.dtype, x.sum().item(), x.mean(1).tolist(), (x @ x.T).tolist(), x.argmax(1).tolist())
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
b = torch.tensor([4.0, 5.0, 6.0], requires_grad=True)
loss = (a * b).sum() + (a ** 2).mean() + torch.tanh(a).sum()
loss.backward()
print([round(v, 4) for v in a.grad.tolist()], b.grad.tolist())

torch.manual_seed(0)
model = nn.Sequential(nn.Linear(1, 8), nn.Tanh(), nn.Linear(8, 1))
opt = torch.optim.Adam(model.parameters(), lr=0.05)
xs = torch.linspace(-1.0, 1.0, 16).unsqueeze(1)
ys = 2.0 * xs
first = None
for step in range(60):
    opt.zero_grad()
    out = model(xs)
    l = F.mse_loss(out, ys)
    l.backward()
    opt.step()
    if first is None:
        first = l.item()
print("trained", first > 0.5, l.item() < first / 10)

torch.save({"model": model.state_dict(), "step": 60}, "ck.pt")
loaded = torch.load("ck.pt")
same = all(torch.equal(loaded["model"][k], v) for k, v in model.state_dict().items())
print("checkpoint", loaded["step"], same, sorted(loaded["model"].keys())[:2])

cell = nn.GRUCell(4, 6)
h = cell(torch.zeros(2, 4), torch.zeros(2, 6))
print(h.shape, F.softmax(torch.tensor([1.0, 2.0, 3.0]), 0).sum().item())
"#;
    let out = run(source).unwrap();
    assert_eq!(
        out,
        vec![
            "torch.Size([2, 2]) torch.float32 10.0 [1.5, 3.5] [[5.0, 11.0], [11.0, 25.0]] [1, 1]",
            "[5.0866, 6.404, 8.0099] [1.0, 2.0, 3.0]",
            "trained True True",
            "checkpoint 60 True ['0.bias', '0.weight']",
            "torch.Size([2, 6]) 1.0",
        ]
    );
}

#[test]
fn compiled_inference_records_graphs_and_preserves_cpu_torch() {
    let output = run(r#"
import torch
import torch.nn as nn
model = nn.Sequential(nn.Linear(2, 3), nn.ReLU(), nn.Linear(3, 1))
with torch.no_grad():
    for parameter in model.parameters():
        parameter.fill_(0.5)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
expected = model(x).tolist()
pending = torch.compile(model)(x)
print(pending.shape)
def done(value):
    print(value.tolist() == expected, pending.backend)
pending.submit(done)
@torch.compile
def square_sum(a):
    return (a * a + 1.0).sum()
square_sum(x).submit(lambda value: print(value.item()))
for action in [lambda: torch.tensor([1.0], device='cuda'), lambda: x.to('gpu'), lambda: model.to('cuda'), lambda: torch.device('cuda')]:
    try:
        action()
    except RuntimeError:
        print('unsupported device rejected')
try:
    pending.backward()
except NotImplementedError:
    print('inference only')
"#).unwrap();
    assert_eq!(output[0], "torch.Size([2, 1])");
    assert!(output[1].starts_with("True "));
    assert_eq!(output[2], "34.0");
    assert_eq!(&output[3..7], ["unsupported device rejected"; 4]);
    assert_eq!(output[7], "inference only");
}

#[test]
fn compiled_training_accumulates_shared_and_input_gradients() {
    let out = run(r#"
import torch
from torch import nn
x = torch.tensor([[1.0, -2.0], [0.0, 3.0]], requires_grad=True)
w = nn.Parameter(torch.tensor([[0.5, -0.25], [0.75, 0.25]]))
b = nn.Parameter(torch.tensor(0.125))
optimizer = torch.optim.SGD([{'params': [w], 'lr': 0.01}, {'params': [b], 'lr': 0.02}], maximize=True)
def step(x):
    optimizer.zero_grad()
    a = x @ w
    # Shared weight, shared branch, scalar broadcasting, transpose, square,
    # reductions and scalar division all contribute to the same leaves.
    loss = ((a + (x @ w) - b) ** 2).sum() / 4.0 + a.T.mean()
    loss.backward()
    optimizer.step()
    return loss
original_w = w.detach().clone()
original_b = b.detach().clone()
expected = []
for i in range(2):
    loss = step(x)
    expected.append([loss.item(), w.detach().clone(), b.detach().clone(), w.grad.clone(), b.grad.clone(), x.grad.clone()])
w.data = original_w
b.data = original_b
x.grad = None
compiled = torch.compile(step, training=True)
index = 0
def done(loss):
    global index
    e = expected[index]
    assert abs(loss.item() - e[0]) < 1e-5
    for actual, wanted in zip([w, b, w.grad, b.grad, x.grad], e[1:]):
        assert torch.allclose(actual, wanted, atol=1e-5), str(actual.tolist())
    index += 1
for i in range(2):
    compiled(x).submit(done)
print('shared and input gradients', index)
"#).unwrap();
    assert_eq!(out, ["shared and input gradients 2"]);
}

#[test]
fn compiled_training_preserves_leaf_grad_across_no_grad() {
    let source = format!(
        "{}\n{}",
        include_str!("fixtures/torch_training_edges.py"),
        r#"
compiled = torch.compile(step, training=True)
compiled(x).submit(lambda loss: print(loss.item(), [round(v, 5) for v in values()]))
"#
    );
    assert_eq!(run(&source).unwrap(), ["202.0 [1.9, 3.0, 1.0, 7.0]"]);
}

#[test]
fn compiled_training_rejects_optimizer_changes_since_capture() {
    let fixture = include_str!("fixtures/torch_training_edges.py");
    for option in [
        "lr",
        "weight_decay",
        "maximize",
        "momentum",
        "dampening",
        "nesterov",
        "append",
        "replace",
        "remove",
        "add_group",
        "reorder_groups",
        "remove_group",
        "remove_option",
    ] {
        let source = format!(
            "{fixture}\noption = {option:?}\n{}",
            r#"
pending = torch.compile(step, training=True)(x)
change_optimizer(option)
pending.submit(lambda loss: print('unexpected success'), lambda error: print(str(error)))
print(values())
"#
        );
        assert_eq!(
            run(&source).unwrap(),
            [
                "GPU training result is stale; optimizer changed before completion",
                "[2.0, 3.0, 11.0, 7.0]"
            ],
            "{option}"
        );
    }
}

/// The training steps `torch.compile(training=True)` captures through the
/// graph protocol's second version, each checked against PyTorch.
const TRAINING_V2_CASES: [&str; 10] = [
    "relu_mse_sgd",
    "gelu_ce_sgd",
    "gelutanh_ce_sgd",
    "sigmoid_ce_momentum",
    "tanh_ce_nesterov",
    "gelu_ce_adam",
    "relu_softmaxmse_adam",
    "tanh_softce_adamw",
    "sigmoid_logsoftmaxnll_momentum",
    "relu_centeredmse_sgd",
];

#[test]
fn compiled_training_v2_matches_pytorch_activations_losses_and_optimizers() {
    // Golden values generated by CPU PyTorch 2.11 (`py -3.11`): for four
    // sequential steps, the loss, every gradient, every weight and the
    // optimizer's state buffers (momentum buffer, Adam moments and step),
    // by running the fixture eagerly with `case` set to each name. Measured
    // deviations are ulp-level (max 2.4e-7 on losses, 1.2e-7 on weights).
    let fixture = include_str!("fixtures/torch_training_v2.py");
    let expected = include_str!("fixtures/torch_training_v2_expected.json");
    for case in TRAINING_V2_CASES {
        let source = format!(
            "case = {case:?}\n{fixture}\nexpected = {expected}\nexpected = expected[case]\n{}",
            r#"
compiled = torch.compile(train_step, training=True)
index = 0
def done(loss):
    global index
    actual = state(loss)
    assert len(actual) == len(expected[index]), (len(actual), len(expected[index]))
    worst = max(abs(a - b) for a, b in zip(actual, expected[index]))
    assert worst < 2e-6, "step %d deviates by %g" % (index, worst)
    index += 1
for step in range(len(expected)):
    compiled(inputs, classes).submit(done)
print(case, 'parity', index)
"#
        );
        assert_eq!(run(&source).unwrap(), [format!("{case} parity 4")], "{case}");
    }
}

#[test]
fn compiled_optimizer_state_continues_into_eager_steps() {
    // Two compiled steps write the momentum buffer / Adam moments and step
    // count into `optimizer.state` under the eager keys, so two eager steps
    // continue the same PyTorch trajectory.
    let fixture = include_str!("fixtures/torch_training_v2.py");
    let expected = include_str!("fixtures/torch_training_v2_expected.json");
    for case in ["sigmoid_ce_momentum", "tanh_softce_adamw"] {
        let source = format!(
            "case = {case:?}\n{fixture}\nexpected = {expected}\nexpected = expected[case]\n{}",
            r#"
compiled = torch.compile(train_step, training=True)
seen = []
def check(loss):
    actual = state(loss)
    worst = max(abs(a - b) for a, b in zip(actual, expected[len(seen)]))
    assert len(actual) == len(expected[len(seen)]) and worst < 1e-5, worst
    seen.append(1)
for step in range(2):
    compiled(inputs, classes).submit(check)
for step in range(2):
    check(train_step(inputs, classes))
print(case, len(seen), sorted(set(str(entry.get("step")) for entry in optimizer.state.values())))
"#
        );
        let steps = if case.ends_with("adamw") { "['4']" } else { "['None']" };
        assert_eq!(run(&source).unwrap(), [format!("{case} 4 {steps}")], "{case}");
    }
}

#[test]
fn compiled_dense_relu_sgd_stays_on_protocol_version_one() {
    // Dense layers, relu, MSE and plain SGD (the first release's scope) must
    // keep recording a version-1 graph: natively that graph runs on the
    // tensor kernels, and a version-1 host still understands it.
    let source = format!(
        "{}\n{}",
        include_str!("fixtures/torch_training.py"),
        r#"
pending = torch.compile(train_step, training=True)(inputs, targets)
graph = pending._value._capture.graph
print(graph.program(loss=pending._value._value)["version"])
pending.submit(lambda loss: print(round(loss.item(), 6)))
"#
    );
    assert_eq!(run(&source).unwrap(), ["1", "0.089844"]);
}

#[test]
fn compiled_training_rejects_what_the_graph_cannot_express() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
targets = torch.tensor([0, 1])
model = nn.Linear(2, 3)
def attempt(name, loss_fn, optimizer=None):
    optimizer = optimizer or torch.optim.SGD(model.parameters(), lr=0.1)
    def step(x, targets):
        optimizer.zero_grad()
        loss = loss_fn(model(x), targets)
        loss.backward()
        optimizer.step()
        return loss
    try:
        torch.compile(step, training=True)(x, targets)
        print(name, 'accepted')
    except (NotImplementedError, TypeError, ValueError) as error:
        print(name, '->', error)
attempt('amsgrad', F.cross_entropy, torch.optim.Adam(model.parameters(), amsgrad=True))
attempt('rmsprop', F.cross_entropy, torch.optim.RMSprop(model.parameters()))
attempt('softmax dim 0', lambda o, t: F.softmax(o, dim=0).sum())
attempt('nll_loss', lambda o, t: F.nll_loss(F.log_softmax(o, -1), t))
attempt('label smoothing', lambda o, t: F.cross_entropy(o, t, label_smoothing=0.1))
attempt('reduction none', lambda o, t: F.cross_entropy(o, t, reduction='none').sum())
attempt('targets rank 2', lambda o, t: F.cross_entropy(o, t.reshape(2, 1)))
attempt('targets out of range', lambda o, t: F.cross_entropy(o, torch.tensor([0, 7])))
attempt('two dims', lambda o, t: (o * o).sum((0, 1)))
attempt('float64', lambda o, t: o.sum(dtype=torch.float64))
attempt('integer arithmetic', lambda o, t: (o + t.reshape(2, 1)).sum())
attempt('gelu tanh form', lambda o, t: F.gelu(o, approximate='tanh').sum())
attempt('sum reduction', lambda o, t: F.cross_entropy(o, t, reduction='sum'))
attempt('soft targets', lambda o, t: F.cross_entropy(o, torch.tensor([[0.2, 0.3, 0.5], [1.0, 0.0, 0.0]])))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "amsgrad -> GPU Adam does not support amsgrad",
            "rmsprop -> Compiled GPU training supports SGD, Adam and AdamW; RMSprop is not captured",
            "softmax dim 0 -> GPU softmax supports the last dimension of a tensor with at least one dimension",
            "nll_loss -> GPU nll_loss is not captured; use F.cross_entropy on the logits with integer class targets",
            "label smoothing -> GPU cross_entropy supports no class weights or label smoothing",
            "reduction none -> GPU cross_entropy supports reduction='mean' or 'sum'",
            "targets rank 2 -> GPU cross_entropy supports class targets of shape [N] for logits [N, C]",
            "targets out of range -> cross_entropy targets must be a tensor of integer class indices in [0, C)",
            "two dims -> GPU sum reduces all elements or one dimension",
            "float64 -> GPU sum computes float32 only",
            "integer arithmetic -> GPU compilation requires float32 tensors; integer tensors are accepted only as cross_entropy class targets",
            "gelu tanh form accepted",
            "sum reduction accepted",
            "soft targets accepted",
        ]
    );
}

#[test]
fn compiled_training_rejects_optimizer_state_changes_since_capture() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
model = nn.Linear(2, 1)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = torch.tensor([[1.0], [0.0]])
def make(optimizer):
    def step(x, y):
        optimizer.zero_grad()
        loss = F.mse_loss(model(x), y)
        loss.backward()
        optimizer.step()
        return loss
    return torch.compile(step, training=True), step
report = lambda error: print(str(error))
before = model.weight.detach().clone()
sgd = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
compiled, eager = make(sgd)
compiled(x, y).submit(lambda loss: print(sorted(sgd.state[id(model.weight)])))
pending = compiled(x, y)
sgd.state[id(model.weight)]['momentum_buffer'] = torch.zeros(1, 2)
pending.submit(lambda loss: print('unexpected'), report)
pending = compiled(x, y)
sgd.state.clear()
pending.submit(lambda loss: print('unexpected'), report)
adam = torch.optim.Adam(model.parameters())
compiled, eager = make(adam)
compiled(x, y).submit(lambda loss: print(adam.state[id(model.weight)]['step']))
pending = compiled(x, y)
eager(x, y)
pending.submit(lambda loss: print('unexpected'), report)
print(adam.state[id(model.weight)]['step'], torch.equal(model.weight, before))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "['momentum_buffer']",
            "GPU training result is stale; optimizer state changed before completion",
            "GPU training result is stale; optimizer state changed before completion",
            "1",
            "GPU training result is stale; optimizer changed before completion",
            "2 False",
        ]
    );
}
