//! The bundled `torch` subset: tensors, autograd, `nn`, `optim` and a
//! checkpoint round trip through the virtual filesystem, all on the
//! runtime's CPU kernels.
#![cfg(feature = "python")]
use zipp_vm::frontend::compile_python_program;

fn run(source: &str) -> Result<Vec<String>, String> {
    let source = source.to_owned();
    std::thread::Builder::new()
        .stack_size(256 << 20)
        .spawn(move || {
            let modules = vec![("main".to_owned(), source)];
            let mut compiled = compile_python_program("main", &modules, &[], &[], false)?;
            let state = compiled.state_mut();
            state.set_limits(400_000_000, None);
            state.run_init()?;
            Ok(state.take_output())
        })
        .expect("spawn")
        .join()
        .expect("test thread")
}

#[test]
fn compiled_training_matches_pytorch_gradients_and_sgd() {
    // Golden values generated by CPU PyTorch 2.11: loss, every parameter's
    // gradient and updated weight, across five sequential training steps.
    let source = format!(
        "{}\nexpected = {}\n{}",
        include_str!("fixtures/torch_training.py"),
        include_str!("fixtures/torch_training_expected.json"),
        r#"
compiled = torch.compile(train_step, training=True)
index = 0
def done(loss):
    global index
    actual = state(loss)
    assert len(actual) == len(expected[index])
    assert all(abs(a-b) < 2e-6 for a,b in zip(actual, expected[index])), str(actual)
    index += 1
for step in range(5):
    pending = compiled(inputs, targets)
    pending.submit(done)
print('training parity', index)
"#
    );
    assert_eq!(run(&source).unwrap(), ["training parity 5"]);
}

#[test]
fn conv2d_matches_pytorch_forward_gradients_and_optimizer() {
    let out = run(include_str!("fixtures/torch_conv2d.py")).unwrap();
    assert_eq!(
        out,
        [
            "conv2d case 0 passed",
            "conv2d case 1 passed",
            "conv2d case 2 passed",
            "conv2d case 3 passed",
            "conv2d optimizer passed"
        ]
    );
}

#[test]
fn conv2d_rejects_unsupported_shapes_and_options() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.ones(1, 2, 3, 3)
w = torch.ones(2, 2, 2, 2)
for action in [lambda: F.conv2d(x,w,stride=0), lambda: F.conv2d(x,w,padding=-1), lambda: F.conv2d(x,w,groups=2), lambda: F.conv2d(x,w,torch.ones(3)), lambda: nn.Conv2d(2,3,3,groups=2), lambda: nn.Conv2d(1,1,3,device='cuda'), lambda: nn.Conv2d(1,1,3,padding_mode='reflect'), lambda: F.conv2d(torch.ones(1,2,1,1),w)]:
    try:
        action()
        print('not rejected')
    except (ValueError, RuntimeError, NotImplementedError):
        print('rejected')
try:
    torch.compile(nn.Conv2d(2,2,1))(x)
except NotImplementedError:
    print('CPU only')
"#).unwrap();
    assert_eq!(&out[..8], ["rejected"; 8]);
    assert_eq!(out[8], "CPU only");
}

#[test]
fn tensors_autograd_modules_and_checkpoints() {
    let source = r#"
import torch
import torch.nn.functional as F
from torch import nn

x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x.shape, x.dtype, x.sum().item(), x.mean(1).tolist(), (x @ x.T).tolist(), x.argmax(1).tolist())
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
b = torch.tensor([4.0, 5.0, 6.0], requires_grad=True)
loss = (a * b).sum() + (a ** 2).mean() + torch.tanh(a).sum()
loss.backward()
print([round(v, 4) for v in a.grad.tolist()], b.grad.tolist())

torch.manual_seed(0)
model = nn.Sequential(nn.Linear(1, 8), nn.Tanh(), nn.Linear(8, 1))
opt = torch.optim.Adam(model.parameters(), lr=0.05)
xs = torch.linspace(-1.0, 1.0, 16).unsqueeze(1)
ys = 2.0 * xs
first = None
for step in range(60):
    opt.zero_grad()
    out = model(xs)
    l = F.mse_loss(out, ys)
    l.backward()
    opt.step()
    if first is None:
        first = l.item()
print("trained", first > 0.5, l.item() < first / 10)

torch.save({"model": model.state_dict(), "step": 60}, "ck.pt")
loaded = torch.load("ck.pt")
same = all(torch.equal(loaded["model"][k], v) for k, v in model.state_dict().items())
print("checkpoint", loaded["step"], same, sorted(loaded["model"].keys())[:2])

cell = nn.GRUCell(4, 6)
h = cell(torch.zeros(2, 4), torch.zeros(2, 6))
print(h.shape, F.softmax(torch.tensor([1.0, 2.0, 3.0]), 0).sum().item())
"#;
    let out = run(source).unwrap();
    assert_eq!(
        out,
        vec![
            "torch.Size([2, 2]) torch.float32 10.0 [1.5, 3.5] [[5.0, 11.0], [11.0, 25.0]] [1, 1]",
            "[5.0866, 6.404, 8.0099] [1.0, 2.0, 3.0]",
            "trained True True",
            "checkpoint 60 True ['0.bias', '0.weight']",
            "torch.Size([2, 6]) 1.0",
        ]
    );
}

#[test]
fn compiled_inference_records_graphs_and_preserves_cpu_torch() {
    let output = run(r#"
import torch
import torch.nn as nn
model = nn.Sequential(nn.Linear(2, 3), nn.ReLU(), nn.Linear(3, 1))
with torch.no_grad():
    for parameter in model.parameters():
        parameter.fill_(0.5)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
expected = model(x).tolist()
pending = torch.compile(model)(x)
print(pending.shape)
def done(value):
    print(value.tolist() == expected, pending.backend)
pending.submit(done)
@torch.compile
def square_sum(a):
    return (a * a + 1.0).sum()
square_sum(x).submit(lambda value: print(value.item()))
for action in [lambda: torch.tensor([1.0], device='cuda'), lambda: x.to('gpu'), lambda: model.to('cuda'), lambda: torch.device('cuda')]:
    try:
        action()
    except RuntimeError:
        print('unsupported device rejected')
try:
    pending.backward()
except NotImplementedError:
    print('inference only')
"#).unwrap();
    assert_eq!(output[0], "torch.Size([2, 1])");
    assert!(output[1].starts_with("True "));
    assert_eq!(output[2], "34.0");
    assert_eq!(&output[3..7], ["unsupported device rejected"; 4]);
    assert_eq!(output[7], "inference only");
}

#[test]
fn compiled_training_accumulates_shared_and_input_gradients() {
    let out = run(r#"
import torch
from torch import nn
x = torch.tensor([[1.0, -2.0], [0.0, 3.0]], requires_grad=True)
w = nn.Parameter(torch.tensor([[0.5, -0.25], [0.75, 0.25]]))
b = nn.Parameter(torch.tensor(0.125))
optimizer = torch.optim.SGD([{'params': [w], 'lr': 0.01}, {'params': [b], 'lr': 0.02}], maximize=True)
def step(x):
    optimizer.zero_grad()
    a = x @ w
    # Shared weight, shared branch, scalar broadcasting, transpose, square,
    # reductions and scalar division all contribute to the same leaves.
    loss = ((a + (x @ w) - b) ** 2).sum() / 4.0 + a.T.mean()
    loss.backward()
    optimizer.step()
    return loss
original_w = w.detach().clone()
original_b = b.detach().clone()
expected = []
for i in range(2):
    loss = step(x)
    expected.append([loss.item(), w.detach().clone(), b.detach().clone(), w.grad.clone(), b.grad.clone(), x.grad.clone()])
w.data = original_w
b.data = original_b
x.grad = None
compiled = torch.compile(step, training=True)
index = 0
def done(loss):
    global index
    e = expected[index]
    assert abs(loss.item() - e[0]) < 1e-5
    for actual, wanted in zip([w, b, w.grad, b.grad, x.grad], e[1:]):
        assert torch.allclose(actual, wanted, atol=1e-5), str(actual.tolist())
    index += 1
for i in range(2):
    compiled(x).submit(done)
print('shared and input gradients', index)
"#).unwrap();
    assert_eq!(out, ["shared and input gradients 2"]);
}

#[test]
fn compiled_training_preserves_leaf_grad_across_no_grad() {
    let source = format!(
        "{}\n{}",
        include_str!("fixtures/torch_training_edges.py"),
        r#"
compiled = torch.compile(step, training=True)
compiled(x).submit(lambda loss: print(loss.item(), [round(v, 5) for v in values()]))
"#
    );
    assert_eq!(run(&source).unwrap(), ["202.0 [1.9, 3.0, 1.0, 7.0]"]);
}

#[test]
fn compiled_training_rejects_optimizer_changes_since_capture() {
    let fixture = include_str!("fixtures/torch_training_edges.py");
    for option in [
        "lr",
        "weight_decay",
        "maximize",
        "momentum",
        "dampening",
        "nesterov",
        "append",
        "replace",
        "remove",
        "add_group",
        "reorder_groups",
        "remove_group",
        "remove_option",
    ] {
        let source = format!(
            "{fixture}\noption = {option:?}\n{}",
            r#"
pending = torch.compile(step, training=True)(x)
change_optimizer(option)
pending.submit(lambda loss: print('unexpected success'), lambda error: print(str(error)))
print(values())
"#
        );
        assert_eq!(
            run(&source).unwrap(),
            [
                "GPU training result is stale; optimizer changed before completion",
                "[2.0, 3.0, 11.0, 7.0]"
            ],
            "{option}"
        );
    }
}
