//! `torch.compile` beyond dense layers: eager operations on parameters inside
//! a compiled training step, views, permutations, division, square roots,
//! multi-dimensional reductions and vectors, compared with PyTorch, with
//! eager Zipp and between per-call and prepared execution; and the cases the
//! graph cannot express, which must raise instead of training silently wrong.
#![cfg(feature = "python")]
use zipp_vm::frontend::compile_python_program;

fn run(source: &str) -> Result<Vec<String>, String> {
    let source = source.to_owned();
    std::thread::Builder::new()
        .stack_size(256 << 20)
        .spawn(move || {
            let modules = vec![("main".to_owned(), source)];
            let mut compiled = compile_python_program("main", &modules, &[], &[], false)?;
            let state = compiled.state_mut();
            state.set_limits(400_000_000, None);
            state.run_init()?;
            Ok(state.take_output())
        })
        .expect("spawn")
        .join()
        .expect("test thread")
}

/// The feature fixture's cases (see fixtures/torch_gpu/features.py).
const FEATURE_CASES: [&str; 10] = [
    "l2reg",
    "tied",
    "eagerops",
    "addparam",
    "detach",
    "shapes",
    "layernorm",
    "arith",
    "softmaxdim",
    "vector",
];

#[test]
fn compiled_features_match_pytorch_per_call_prepared_and_eager() {
    // Golden values generated by CPU PyTorch 2.11 (`python`, 3.11): one
    // state vector (loss, gradients, weights, optimizer buffers and step
    // count) per eager step over four distinct batches. Each case runs as
    // chained compiled calls, as eager Zipp and as one prepared session (a
    // single step, then the rest in one submission, then `sync()`); the
    // prepared losses and final state must equal the chained calls' bit for
    // bit. Measured deviations from PyTorch are below 1.3e-7 (relative to
    // 1 + |value|).
    let fixture = include_str!("fixtures/torch_gpu/features.py");
    let expected = include_str!("fixtures/torch_gpu/features_expected.json");
    for case in FEATURE_CASES {
        let source = format!(
            "case = {case:?}\n{fixture}\nexpected = {expected}\nexpected = expected[case]\n{}",
            r#"
compiled = torch.compile(train_step, training=True)
initial = [p.detach().clone() for p in params]
def reset():
    for p, value in zip(params, initial):
        p.data = value.clone()
        p.grad = None
    optimizer.state.clear()
def worst(actual, wanted):
    assert len(actual) == len(wanted), (len(actual), len(wanted))
    return max(abs(a - b) / (1.0 + abs(b)) for a, b in zip(actual, wanted))
chained, chained_losses = [], []
def took(loss):
    chained_losses.append(loss.item())
    chained.append(state(loss))
for x, y in batches:
    compiled(x, y).submit(took)
assert len(chained) == STEPS
deviation = max(worst(s, e) for s, e in zip(chained, expected))
assert deviation < 1e-6, "compiled deviates by %g" % deviation
reset()
eager = [state(train_step(x, y)) for x, y in batches]
deviation = max(worst(s, e) for s, e in zip(eager, expected))
assert deviation < 1e-6, "eager deviates by %g" % deviation
reset()
prepared = compiled.prepare(*batches[0])
resident = []
prepared.step(lambda loss: resident.append(loss.item()), *batches[0])
prepared.steps(lambda results: resident.extend(r.item() for r in results), batches[1:])
prepared.sync(lambda p: None)
final = state(torch.tensor(resident[-1]))
prepared.dispose()
deviation = worst(final, expected[-1])
assert deviation < 1e-6, "prepared deviates by %g" % deviation
print(case, resident == chained_losses, final == chained[-1])
"#
        );
        assert_eq!(run(&source).unwrap(), [format!("{case} True True")], "{case}");
    }
}

#[test]
fn eager_operations_on_parameters_keep_their_gradient_path() {
    // `W.T`, `W * 2`, `(p ** 2).sum()` and `torch.add(h, b)` inside a
    // compiled step run eagerly on the parameter; the capture re-records
    // them on the parameter's own input, so the gradient reaches it (these
    // used to become separate leaves: a silently partial gradient, or a
    // parameter "not participating"). What it cannot record raises.
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.tensor([[1.0, 2.0, 0.5], [3.0, -1.0, 0.2], [0.5, 0.5, -1.0]])
def run(kind, compiled):
    W = nn.Parameter(torch.tensor([[0.5, -0.2, 0.3], [0.1, 0.3, -0.4]]))
    b = nn.Parameter(torch.tensor([0.1, -0.1]))
    optimizer = torch.optim.SGD([W, b], lr=0.1)
    def step(x):
        optimizer.zero_grad()
        if kind == "tied":
            loss = ((torch.tanh(x @ W.T + b) @ W - x) ** 2).mean()
        elif kind == "scaled only":
            loss = ((x @ (W * 2.0).T + b) ** 2).mean()
        elif kind == "add":
            loss = ((torch.add(torch.tanh(W @ x.T).T, b) + b) ** 2).mean()
        elif kind == "l2":
            loss = (x @ W.T + b).square().mean() + 0.5 * sum((p ** 2).sum() for p in (W, b))
        elif kind == "clamp":
            loss = (x @ W.clamp(-0.25, 0.25).T + b).square().mean()
        elif kind == "slice":
            loss = (x @ W.T + b).square().mean() + W[0].sum()
        else:
            loss = (x @ W.T + b).square().mean() + (W ** 3).sum()
        loss.backward()
        optimizer.step()
        return loss
    if not compiled:
        step(x)
    else:
        torch.compile(step, training=True)(x).submit(lambda loss: None)
    return W.grad.tolist() + [b.grad.tolist()], W.tolist()
for kind in ("tied", "scaled only", "add", "l2"):
    eager, compiled = run(kind, False), run(kind, True)
    grads = max(abs(p - q) for a, c in zip(eager[0], compiled[0]) for p, q in zip(a, c))
    weights = max(abs(p - q) for a, c in zip(eager[1], compiled[1]) for p, q in zip(a, c))
    print(kind, grads < 1e-6, weights < 1e-6)
for kind in ("clamp", "slice", "cube"):
    try:
        run(kind, True)
        print(kind, "accepted")
    except NotImplementedError as error:
        print(kind, "->", error)
"#)
    .unwrap();
    let unsupported = |name: &str| {
        format!(
            "torch.compile cannot record the eager operation {name} applied to a parameter inside a compiled training step \
             (its gradient would not reach the parameter); apply it to graph tensors or outside the step"
        )
    };
    assert_eq!(
        out,
        [
            "tied True True".to_owned(),
            "scaled only True True".to_owned(),
            "add True True".to_owned(),
            "l2 True True".to_owned(),
            format!("clamp -> {}", unsupported("Clamp")),
            format!("slice -> {}", unsupported("Slice")),
            "cube -> GPU power supports the exponents 2, 1, 0.5, -1 and -0.5".to_owned(),
        ]
    );
}

#[test]
fn prepared_feeds_class_targets_read_through_views() {
    // A class-target argument the step reshapes before use (`y.view(-1)`,
    // `.reshape`, `.squeeze`, `.flatten`, `.long()` on int64) shares the
    // argument's storage: it is fed from the argument every step. It used to
    // be recorded as a constant, training every step on the prepare-time
    // labels. A copy derived from the argument (a slice, a dtype cast) or an
    // argument the step ignores cannot be fed and is refused at prepare().
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
def make():
    model = nn.Linear(3, 3)
    with torch.no_grad():
        model.weight.copy_(torch.tensor([[0.5, -0.2, 0.3], [0.1, 0.3, -0.4], [0.2, 0.2, 0.2]]))
        model.bias.copy_(torch.tensor([0.1, -0.1, 0.0]))
    return model, torch.optim.SGD(model.parameters(), lr=0.1)
x0 = torch.tensor([[1.0, 2.0, 0.5], [3.0, -1.0, 0.2], [0.5, 0.5, -1.0], [0.0, 1.0, 1.0]])
x1 = x0 * -0.5 + 0.25
y0 = torch.tensor([[0], [1], [2], [0]])
y1 = torch.tensor([[2], [2], [0], [1]])
derive = {
    "view(-1)": lambda y: y.view(-1),
    "reshape(-1)": lambda y: y.reshape(-1),
    "squeeze(1)": lambda y: y.squeeze(1),
    "flatten()": lambda y: y.flatten(),
    "long().view(-1)": lambda y: y.long().view(-1),
    "y[:, 0]": lambda y: y[:, 0],
    "y.int()": lambda y: y.int().view(-1),
}
for name, fn in derive.items():
    def losses(prepared):
        model, optimizer = make()
        def step(x, y):
            optimizer.zero_grad()
            loss = F.cross_entropy(model(x), fn(y))
            loss.backward()
            optimizer.step()
            return loss
        if not prepared:
            return [step(x0, y0).item(), step(x1, y1).item()]
        session = torch.compile(step, training=True).prepare(x0, y0)
        got = []
        session.steps(lambda results: got.extend(r.item() for r in results), [(x0, y0), (x1, y1)])
        session.dispose()
        return got
    try:
        eager, prepared = losses(False), losses(True)
        print(name, [round(v, 5) for v in prepared], max(abs(a - b) for a, b in zip(eager, prepared)) < 1e-6)
    except NotImplementedError as error:
        print(name, "->", error)
model, optimizer = make()
def mse_step(x, t):
    optimizer.zero_grad()
    loss = F.mse_loss(model(x), t.float())
    loss.backward()
    optimizer.step()
    return loss
def unused_step(x, t):
    optimizer.zero_grad()
    loss = model(x).square().mean()
    loss.backward()
    optimizer.step()
    return loss
for name, step in (("t.float()", mse_step), ("unused argument", unused_step)):
    try:
        torch.compile(step, training=True).prepare(x0, torch.ones(4, 3, dtype=torch.int64))
        print(name, "accepted")
    except NotImplementedError as error:
        print(name, "->", error)
# Per call, a derived copy is recorded afresh each call: still accepted (PyTorch: 0.67588).
torch.compile(mse_step, training=True)(x0, torch.ones(4, 3, dtype=torch.int64)).submit(lambda loss: print("per-call t.float()", round(loss.item(), 5)))
"#)
    .unwrap();
    let refused = |position: &str| {
        format!(
            "prepare(): tensor argument {position} is not read by the recorded step as a feed; the step ignores it or derives a copy \
             from it (a slice, a dtype cast, arithmetic), which the session would freeze at its prepare() value. \
             Pass the derived tensor as the argument instead"
        )
    };
    let fed = "[1.48578, 1.0207] True";
    assert_eq!(
        out,
        [
            format!("view(-1) {fed}"),
            format!("reshape(-1) {fed}"),
            format!("squeeze(1) {fed}"),
            format!("flatten() {fed}"),
            format!("long().view(-1) {fed}"),
            format!("y[:, 0] -> {}", refused("1")),
            format!("y.int() -> {}", refused("1")),
            format!("t.float() -> {}", refused("1")),
            format!("unused argument -> {}", refused("1")),
            "per-call t.float() 0.67588".to_owned(),
        ]
    );
}

#[test]
fn prepared_steps_refuse_cpu_random_draws_and_values_a_step_would_change() {
    // A prepared session replays one recorded program: torch.randn noise
    // drawn on the CPU while recording would be the same at every step, so
    // prepare() refuses it (per-call compilation draws afresh each call and
    // still accepts it). Dropout draws its mask on the device, afresh every
    // step, and is accepted. A constant the step builds is uploaded once and
    // accepted; a value computed from a parameter under no_grad or a one-hot
    // of the targets would be frozen and is refused, naming why; the scalars
    // eager arithmetic wraps stay accepted (python_torch_gpu2.rs has more).
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
torch.manual_seed(0)
layer = nn.Linear(4, 4)
optimizer = torch.optim.SGD(layer.parameters(), lr=0.0)
x = torch.ones(2, 4)
def make(noise):
    def step(x):
        optimizer.zero_grad()
        h = layer(x)
        if noise == "dropout":
            h = F.dropout(h, p=0.5, training=True)
        elif noise == "nn.Dropout":
            h = nn.Dropout(0.5)(h)
        elif noise == "randn":
            h = h + torch.randn(2, 4)
        elif noise == "eval dropout":
            h = F.dropout(h, p=0.5, training=False)
        loss = (h * h).sum()
        loss.backward()
        optimizer.step()
        return loss
    return torch.compile(step, training=True)
for noise in ("dropout", "nn.Dropout", "randn", "eval dropout"):
    compiled = make(noise)
    losses = []
    for _ in range(3):
        compiled(x).submit(lambda loss: losses.append(loss.item()))
    try:
        compiled.prepare(x).dispose()
        prepared = "accepted"
    except NotImplementedError as error:
        prepared = str(error)
    print(noise, len(set(losses)) > 1, prepared)
print(torch.randn(1).shape)
# Any other tensor the step creates and reads is frozen the same way.
classes = torch.tensor([0, 3])
def make_created(kind):
    def step(x, y):
        optimizer.zero_grad()
        h = layer(x)
        if kind == "constant":
            h = h + torch.ones(2, 4)
        elif kind == "no_grad from a parameter":
            with torch.no_grad():
                scale = layer.weight.abs().sum()
            h = h * scale
        elif kind == "one_hot of a read target":
            h = h + F.one_hot(y, 4).float()
        elif kind == "graph scalars":
            h = h * 2.0 + layer.bias * 0.5 - 1.0
        loss = F.cross_entropy(h, y)
        loss.backward()
        optimizer.step()
        return loss
    return torch.compile(step, training=True)
for kind in ("constant", "no_grad from a parameter", "one_hot of a read target", "graph scalars"):
    try:
        make_created(kind).prepare(x, classes).dispose()
        print(kind, "accepted")
    except NotImplementedError as error:
        print(kind, "->", error)
"#)
    .unwrap();
    let refused = "prepare() cannot record a step that draws random numbers on the CPU (torch.rand/randn/randint/normal...): \
                   the prepared session would replay the same draw at every step. F.dropout, nn.Dropout and torch.rand_like or \
                   torch.bernoulli of graph tensors draw on the device, afresh every step. Use per-call torch.compile, \
                   or draw outside the step and pass the tensor as an argument";
    let parameter = "prepare(): the step reads a tensor computed from a parameter outside autograd (under no_grad, or from \
                     .detach()/.data) as a graph input; the session would keep its prepare() value at every step. Compute it from \
                     the parameter with gradients enabled (it is then recorded on the device from the resident weights) or outside the step";
    let argument = "prepare(): the step reads a tensor that an eager operation derived from a step argument (a one-hot, a cast, \
                    arithmetic on class targets) as a graph input; the session would keep its prepare() value at every step. \
                    Pass the derived tensor as the argument instead";
    assert_eq!(
        out,
        [
            "dropout True accepted".to_owned(),
            "nn.Dropout True accepted".to_owned(),
            format!("randn True {refused}"),
            "eval dropout False accepted".to_owned(),
            "torch.Size([1])".to_owned(),
            "constant accepted".to_owned(),
            format!("no_grad from a parameter -> {parameter}"),
            format!("one_hot of a read target -> {argument}"),
            "graph scalars accepted".to_owned(),
        ]
    );
}

#[test]
fn graph_tensors_raise_not_implemented_for_what_the_graph_cannot_express() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
model = nn.Linear(3, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
x = torch.tensor([[1.0, 2.0, 0.5], [3.0, -1.0, 0.2]])
y = torch.tensor([0, 1])
def attempt(name, body):
    def step(x, y):
        optimizer.zero_grad()
        loss = body(x, y)
        loss.backward()
        optimizer.step()
        return loss
    try:
        torch.compile(step, training=True)(x, y)
        print(name, "accepted")
    except NotImplementedError as error:
        print(name, "->", error)
attempt("torch.erf", lambda x, y: F.cross_entropy(torch.erf(model(x)), y))
attempt("clamp", lambda x, y: F.cross_entropy(model(x).clamp(0, 1), y))
attempt("slice", lambda x, y: F.cross_entropy(model(x)[0:1], y[0:1]))
attempt("gather", lambda x, y: F.cross_entropy(model(x)[:, 0:1], y))
attempt("comparison", lambda x, y: F.cross_entropy(model(x) * (model(x) > 0), y))
attempt("cube", lambda x, y: F.cross_entropy(model(x) ** 3, y))
attempt("item", lambda x, y: F.cross_entropy(model(x), y) * model(x).sum().item())
attempt("hasattr", lambda x, y: F.cross_entropy(model(x), y) * (2.0 if hasattr(x, "grad") else 1.0))
attempt("reshape-only indexing", lambda x, y: F.cross_entropy(model(x)[None][0][:, :, None][..., 0], y))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "torch.erf -> This torch function is not supported by torch.compile: it cannot record it on a compiled graph tensor \
             (the supported operations are listed in docs/TORCH_COMPATIBILITY.md)",
            "clamp accepted",
            "slice -> torch.compile supports indexing that only reshapes (None, full slices, index 0 of a size-1 dimension); \
             slicing and gathering elements are not supported",
            "gather -> torch.compile supports indexing that only reshapes (None, full slices, index 0 of a size-1 dimension); \
             slicing and gathering elements are not supported",
            "comparison accepted",
            "cube -> GPU power supports the exponents 2, 1, 0.5, -1 and -0.5",
            "item -> Tensor.item is not supported by torch.compile",
            "hasattr accepted",
            "reshape-only indexing accepted",
        ]
    );
}

#[test]
fn compiled_inference_takes_vectors_transposes_and_non_last_softmax() {
    // 1-D inputs to nn.Linear and matrix/vector products reshape to
    // matrices; .t(), .square(), softmax over dim 0 and reductions over two
    // dimensions record graph operations. Each compiled result equals the
    // eager one computed from the same operations.
    let out = run(r#"
import torch
from torch import nn
torch.manual_seed(3)
layer = nn.Linear(4, 3)
M = torch.randn(3, 4)
v, w = torch.randn(4), torch.randn(3)
X = torch.randn(3, 4)
programs = {
    "linear on a vector": (lambda v, w, X: layer(v), lambda v, w, X: layer(v.unsqueeze(0)).squeeze(0)),
    "vector @ matrix": (lambda v, w, X: w @ X, lambda v, w, X: (w.unsqueeze(0) @ X).squeeze(0)),
    "matrix @ vector": (lambda v, w, X: X @ v, lambda v, w, X: (X @ v.unsqueeze(1)).squeeze(1)),
    "dot": (lambda v, w, X: v @ v, lambda v, w, X: (v * v).sum()),
    "t and square": (lambda v, w, X: X.t().square(), lambda v, w, X: X.transpose(0, 1) * X.transpose(0, 1)),
    "softmax dim 0": (lambda v, w, X: torch.softmax(X, dim=0), lambda v, w, X: torch.softmax(X, dim=0)),
    "sum over two dims": (lambda v, w, X: X.reshape(3, 2, 2).sum((0, 2)), lambda v, w, X: X.reshape(3, 2, 2).sum((0, 2))),
    "mean over two dims": (lambda v, w, X: X.view(3, 2, 2).mean((1, 2), keepdim=True), lambda v, w, X: X.view(3, 2, 2).mean((1, 2), keepdim=True)),
    "division": (lambda v, w, X: X / (X.abs() + 1.0), lambda v, w, X: X / (X.abs() + 1.0)),
}
for name, (compiled_fn, eager_fn) in programs.items():
    got = []
    torch.compile(compiled_fn)(v, w, X).submit(got.append)
    want = eager_fn(v, w, X)
    print(name, list(got[0].shape) == list(want.shape), torch.allclose(got[0], want, atol=1e-6))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "linear on a vector True True",
            "vector @ matrix True True",
            "matrix @ vector True True",
            "dot True True",
            "t and square True True",
            "softmax dim 0 True True",
            "sum over two dims True True",
            "mean over two dims True True",
            "division True True",
        ]
    );
}
