//! The bundled `torch` subset: tensors, autograd, `nn`, `optim` and a
//! checkpoint round trip through the virtual filesystem, all on the
//! runtime's CPU kernels.
#![cfg(feature = "python")]
use zipp_vm::frontend::compile_python_program;

fn run(source: &str) -> Result<Vec<String>, String> {
    let source = source.to_owned();
    std::thread::Builder::new()
        .stack_size(256 << 20)
        .spawn(move || {
            let modules = vec![("main".to_owned(), source)];
            let mut compiled = compile_python_program("main", &modules, &[], &[], false)?;
            let state = compiled.state_mut();
            state.set_limits(400_000_000, None);
            state.run_init()?;
            Ok(state.take_output())
        })
        .expect("spawn")
        .join()
        .expect("test thread")
}

#[test]
fn compiled_training_matches_pytorch_gradients_and_sgd() {
    // Golden values generated by CPU PyTorch 2.11: loss, every parameter's
    // gradient and updated weight, across five sequential training steps.
    let source = format!(
        "{}\nexpected = {}\n{}",
        include_str!("fixtures/torch_training.py"),
        include_str!("fixtures/torch_training_expected.json"),
        r#"
compiled = torch.compile(train_step, training=True)
index = 0
def done(loss):
    global index
    actual = state(loss)
    assert len(actual) == len(expected[index])
    assert all(abs(a-b) < 2e-6 for a,b in zip(actual, expected[index])), str(actual)
    index += 1
for step in range(5):
    pending = compiled(inputs, targets)
    pending.submit(done)
print('training parity', index)
"#
    );
    assert_eq!(run(&source).unwrap(), ["training parity 5"]);
}

#[test]
fn conv2d_matches_pytorch_forward_gradients_and_optimizer() {
    let out = run(include_str!("fixtures/torch_conv2d.py")).unwrap();
    assert_eq!(
        out,
        [
            "conv2d case 0 passed",
            "conv2d case 1 passed",
            "conv2d case 2 passed",
            "conv2d case 3 passed",
            "conv2d optimizer passed"
        ]
    );
}

#[test]
fn conv2d_rejects_unsupported_shapes_and_options() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.ones(1, 2, 3, 3)
w = torch.ones(2, 2, 2, 2)
for action in [lambda: F.conv2d(x,w,stride=0), lambda: F.conv2d(x,w,padding=-1), lambda: F.conv2d(x,w,groups=2), lambda: F.conv2d(x,w,torch.ones(3)), lambda: nn.Conv2d(2,3,3,groups=2), lambda: nn.Conv2d(1,1,3,device='cuda'), lambda: nn.Conv2d(1,1,3,padding_mode='reflect'), lambda: F.conv2d(torch.ones(1,2,1,1),w)]:
    try:
        action()
        print('not rejected')
    except (ValueError, RuntimeError, NotImplementedError):
        print('rejected')
try:
    torch.compile(nn.Conv2d(2,2,1))(x)
except NotImplementedError:
    print('CPU only')
"#).unwrap();
    assert_eq!(&out[..8], ["rejected"; 8]);
    assert_eq!(out[8], "CPU only");
}

#[test]
fn tensors_autograd_modules_and_checkpoints() {
    let source = r#"
import torch
import torch.nn.functional as F
from torch import nn

x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x.shape, x.dtype, x.sum().item(), x.mean(1).tolist(), (x @ x.T).tolist(), x.argmax(1).tolist())
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
b = torch.tensor([4.0, 5.0, 6.0], requires_grad=True)
loss = (a * b).sum() + (a ** 2).mean() + torch.tanh(a).sum()
loss.backward()
print([round(v, 4) for v in a.grad.tolist()], b.grad.tolist())

torch.manual_seed(0)
model = nn.Sequential(nn.Linear(1, 8), nn.Tanh(), nn.Linear(8, 1))
opt = torch.optim.Adam(model.parameters(), lr=0.05)
xs = torch.linspace(-1.0, 1.0, 16).unsqueeze(1)
ys = 2.0 * xs
first = None
for step in range(60):
    opt.zero_grad()
    out = model(xs)
    l = F.mse_loss(out, ys)
    l.backward()
    opt.step()
    if first is None:
        first = l.item()
print("trained", first > 0.5, l.item() < first / 10)

torch.save({"model": model.state_dict(), "step": 60}, "ck.pt")
loaded = torch.load("ck.pt")
same = all(torch.equal(loaded["model"][k], v) for k, v in model.state_dict().items())
print("checkpoint", loaded["step"], same, sorted(loaded["model"].keys())[:2])

cell = nn.GRUCell(4, 6)
h = cell(torch.zeros(2, 4), torch.zeros(2, 6))
print(h.shape, F.softmax(torch.tensor([1.0, 2.0, 3.0]), 0).sum().item())
"#;
    let out = run(source).unwrap();
    assert_eq!(
        out,
        vec![
            "torch.Size([2, 2]) torch.float32 10.0 [1.5, 3.5] [[5.0, 11.0], [11.0, 25.0]] [1, 1]",
            "[5.0866, 6.404, 8.0099] [1.0, 2.0, 3.0]",
            "trained True True",
            "checkpoint 60 True ['0.bias', '0.weight']",
            "torch.Size([2, 6]) 1.0",
        ]
    );
}

#[test]
fn compiled_inference_records_graphs_and_preserves_cpu_torch() {
    let output = run(r#"
import torch
import torch.nn as nn
model = nn.Sequential(nn.Linear(2, 3), nn.ReLU(), nn.Linear(3, 1))
with torch.no_grad():
    for parameter in model.parameters():
        parameter.fill_(0.5)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
expected = model(x).tolist()
pending = torch.compile(model)(x)
print(pending.shape)
def done(value):
    print(value.tolist() == expected, pending.backend)
pending.submit(done)
@torch.compile
def square_sum(a):
    return (a * a + 1.0).sum()
square_sum(x).submit(lambda value: print(value.item()))
for action in [lambda: torch.tensor([1.0], device='cuda'), lambda: x.to('gpu'), lambda: model.to('cuda'), lambda: torch.device('cuda')]:
    try:
        action()
    except RuntimeError:
        print('unsupported device rejected')
try:
    pending.backward()
except NotImplementedError:
    print('inference only')
"#).unwrap();
    assert_eq!(output[0], "torch.Size([2, 1])");
    assert!(output[1].starts_with("True "));
    assert_eq!(output[2], "34.0");
    assert_eq!(&output[3..7], ["unsupported device rejected"; 4]);
    assert_eq!(output[7], "inference only");
}

#[test]
fn compiled_training_accumulates_shared_and_input_gradients() {
    let out = run(r#"
import torch
from torch import nn
x = torch.tensor([[1.0, -2.0], [0.0, 3.0]], requires_grad=True)
w = nn.Parameter(torch.tensor([[0.5, -0.25], [0.75, 0.25]]))
b = nn.Parameter(torch.tensor(0.125))
optimizer = torch.optim.SGD([{'params': [w], 'lr': 0.01}, {'params': [b], 'lr': 0.02}], maximize=True)
def step(x):
    optimizer.zero_grad()
    a = x @ w
    # Shared weight, shared branch, scalar broadcasting, transpose, square,
    # reductions and scalar division all contribute to the same leaves.
    loss = ((a + (x @ w) - b) ** 2).sum() / 4.0 + a.T.mean()
    loss.backward()
    optimizer.step()
    return loss
original_w = w.detach().clone()
original_b = b.detach().clone()
expected = []
for i in range(2):
    loss = step(x)
    expected.append([loss.item(), w.detach().clone(), b.detach().clone(), w.grad.clone(), b.grad.clone(), x.grad.clone()])
w.data = original_w
b.data = original_b
x.grad = None
compiled = torch.compile(step, training=True)
index = 0
def done(loss):
    global index
    e = expected[index]
    assert abs(loss.item() - e[0]) < 1e-5
    for actual, wanted in zip([w, b, w.grad, b.grad, x.grad], e[1:]):
        assert torch.allclose(actual, wanted, atol=1e-5), str(actual.tolist())
    index += 1
for i in range(2):
    compiled(x).submit(done)
print('shared and input gradients', index)
"#).unwrap();
    assert_eq!(out, ["shared and input gradients 2"]);
}

#[test]
fn compiled_training_preserves_leaf_grad_across_no_grad() {
    let source = format!(
        "{}\n{}",
        include_str!("fixtures/torch_training_edges.py"),
        r#"
compiled = torch.compile(step, training=True)
compiled(x).submit(lambda loss: print(loss.item(), [round(v, 5) for v in values()]))
"#
    );
    assert_eq!(run(&source).unwrap(), ["202.0 [1.9, 3.0, 1.0, 7.0]"]);
}

#[test]
fn compiled_training_rejects_optimizer_changes_since_capture() {
    let fixture = include_str!("fixtures/torch_training_edges.py");
    for option in [
        "lr",
        "weight_decay",
        "maximize",
        "momentum",
        "dampening",
        "nesterov",
        "append",
        "replace",
        "remove",
        "add_group",
        "reorder_groups",
        "remove_group",
        "remove_option",
    ] {
        let source = format!(
            "{fixture}\noption = {option:?}\n{}",
            r#"
pending = torch.compile(step, training=True)(x)
change_optimizer(option)
pending.submit(lambda loss: print('unexpected success'), lambda error: print(str(error)))
print(values())
"#
        );
        assert_eq!(
            run(&source).unwrap(),
            [
                "GPU training result is stale; optimizer changed before completion",
                "[2.0, 3.0, 11.0, 7.0]"
            ],
            "{option}"
        );
    }
}

/// The training steps `torch.compile(training=True)` captures through the
/// graph protocol's second version, each checked against PyTorch.
const TRAINING_V2_CASES: [&str; 10] = [
    "relu_mse_sgd",
    "gelu_ce_sgd",
    "gelutanh_ce_sgd",
    "sigmoid_ce_momentum",
    "tanh_ce_nesterov",
    "gelu_ce_adam",
    "relu_softmaxmse_adam",
    "tanh_softce_adamw",
    "sigmoid_logsoftmaxnll_momentum",
    "relu_centeredmse_sgd",
];

#[test]
fn compiled_training_v2_matches_pytorch_activations_losses_and_optimizers() {
    // Golden values generated by CPU PyTorch 2.11 (`py -3.11`): for four
    // sequential steps, the loss, every gradient, every weight and the
    // optimizer's state buffers (momentum buffer, Adam moments and step),
    // by running the fixture eagerly with `case` set to each name. Measured
    // deviations are ulp-level (max 2.4e-7 on losses, 1.2e-7 on weights).
    let fixture = include_str!("fixtures/torch_training_v2.py");
    let expected = include_str!("fixtures/torch_training_v2_expected.json");
    for case in TRAINING_V2_CASES {
        let source = format!(
            "case = {case:?}\n{fixture}\nexpected = {expected}\nexpected = expected[case]\n{}",
            r#"
compiled = torch.compile(train_step, training=True)
index = 0
def done(loss):
    global index
    actual = state(loss)
    assert len(actual) == len(expected[index]), (len(actual), len(expected[index]))
    worst = max(abs(a - b) for a, b in zip(actual, expected[index]))
    assert worst < 2e-6, "step %d deviates by %g" % (index, worst)
    index += 1
for step in range(len(expected)):
    compiled(inputs, classes).submit(done)
print(case, 'parity', index)
"#
        );
        assert_eq!(run(&source).unwrap(), [format!("{case} parity 4")], "{case}");
    }
}

#[test]
fn compiled_optimizer_state_continues_into_eager_steps() {
    // Two compiled steps write the momentum buffer / Adam moments and step
    // count into `optimizer.state` under the eager keys, so two eager steps
    // continue the same PyTorch trajectory.
    let fixture = include_str!("fixtures/torch_training_v2.py");
    let expected = include_str!("fixtures/torch_training_v2_expected.json");
    for case in ["sigmoid_ce_momentum", "tanh_softce_adamw"] {
        let source = format!(
            "case = {case:?}\n{fixture}\nexpected = {expected}\nexpected = expected[case]\n{}",
            r#"
compiled = torch.compile(train_step, training=True)
seen = []
def check(loss):
    actual = state(loss)
    worst = max(abs(a - b) for a, b in zip(actual, expected[len(seen)]))
    assert len(actual) == len(expected[len(seen)]) and worst < 1e-5, worst
    seen.append(1)
for step in range(2):
    compiled(inputs, classes).submit(check)
for step in range(2):
    check(train_step(inputs, classes))
print(case, len(seen), sorted(set(str(entry.get("step")) for entry in optimizer.state.values())))
"#
        );
        let steps = if case.ends_with("adamw") { "['4']" } else { "['None']" };
        assert_eq!(run(&source).unwrap(), [format!("{case} 4 {steps}")], "{case}");
    }
}

#[test]
fn compiled_dense_relu_sgd_stays_on_protocol_version_one() {
    // Dense layers, relu, MSE and plain SGD (the first release's scope) must
    // keep recording a version-1 graph: natively that graph runs on the
    // tensor kernels, and a version-1 host still understands it.
    let source = format!(
        "{}\n{}",
        include_str!("fixtures/torch_training.py"),
        r#"
pending = torch.compile(train_step, training=True)(inputs, targets)
graph = pending._value._capture.graph
print(graph.program(loss=pending._value._value)["version"])
pending.submit(lambda loss: print(round(loss.item(), 6)))
"#
    );
    assert_eq!(run(&source).unwrap(), ["1", "0.089844"]);
}

#[test]
fn compiled_training_rejects_what_the_graph_cannot_express() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
targets = torch.tensor([0, 1])
model = nn.Linear(2, 3)
def attempt(name, loss_fn, optimizer=None):
    optimizer = optimizer or torch.optim.SGD(model.parameters(), lr=0.1)
    def step(x, targets):
        optimizer.zero_grad()
        loss = loss_fn(model(x), targets)
        loss.backward()
        optimizer.step()
        return loss
    try:
        torch.compile(step, training=True)(x, targets)
        print(name, 'accepted')
    except (NotImplementedError, TypeError, ValueError) as error:
        print(name, '->', error)
attempt('amsgrad', F.cross_entropy, torch.optim.Adam(model.parameters(), amsgrad=True))
attempt('rmsprop', F.cross_entropy, torch.optim.RMSprop(model.parameters()))
attempt('softmax dim 0', lambda o, t: F.softmax(o, dim=0).sum())
attempt('nll_loss', lambda o, t: F.nll_loss(F.log_softmax(o, -1), t))
attempt('label smoothing', lambda o, t: F.cross_entropy(o, t, label_smoothing=0.1))
attempt('reduction none', lambda o, t: F.cross_entropy(o, t, reduction='none').sum())
attempt('targets rank 2', lambda o, t: F.cross_entropy(o, t.reshape(2, 1)))
attempt('targets out of range', lambda o, t: F.cross_entropy(o, torch.tensor([0, 7])))
attempt('two dims', lambda o, t: (o * o).sum((0, 1)))
attempt('float64', lambda o, t: o.sum(dtype=torch.float64))
attempt('integer arithmetic', lambda o, t: (o + t.reshape(2, 1)).sum())
attempt('gelu tanh form', lambda o, t: F.gelu(o, approximate='tanh').sum())
attempt('sum reduction', lambda o, t: F.cross_entropy(o, t, reduction='sum'))
attempt('soft targets', lambda o, t: F.cross_entropy(o, torch.tensor([[0.2, 0.3, 0.5], [1.0, 0.0, 0.0]])))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "amsgrad -> GPU Adam does not support amsgrad",
            "rmsprop -> Compiled GPU training supports SGD, Adam and AdamW; RMSprop is not captured",
            "softmax dim 0 -> GPU softmax supports the last dimension of a tensor with at least one dimension",
            "nll_loss -> GPU nll_loss is not captured; use F.cross_entropy on the logits with integer class targets",
            "label smoothing -> GPU cross_entropy supports no class weights or label smoothing",
            "reduction none -> GPU cross_entropy supports reduction='mean' or 'sum'",
            "targets rank 2 -> GPU cross_entropy supports class targets of shape [N] for logits [N, C]",
            "targets out of range -> cross_entropy targets must be a tensor of integer class indices in [0, C)",
            "two dims -> GPU sum reduces all elements or one dimension",
            "float64 -> GPU sum computes float32 only",
            "integer arithmetic -> GPU compilation requires float32 tensors; integer tensors are accepted only as cross_entropy class targets",
            "gelu tanh form accepted",
            "sum reduction accepted",
            "soft targets accepted",
        ]
    );
}

#[test]
fn compiled_training_rejects_optimizer_state_changes_since_capture() {
    let out = run(r#"
import torch
from torch import nn
import torch.nn.functional as F
model = nn.Linear(2, 1)
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
y = torch.tensor([[1.0], [0.0]])
def make(optimizer):
    def step(x, y):
        optimizer.zero_grad()
        loss = F.mse_loss(model(x), y)
        loss.backward()
        optimizer.step()
        return loss
    return torch.compile(step, training=True), step
report = lambda error: print(str(error))
before = model.weight.detach().clone()
sgd = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
compiled, eager = make(sgd)
compiled(x, y).submit(lambda loss: print(sorted(sgd.state[id(model.weight)])))
pending = compiled(x, y)
sgd.state[id(model.weight)]['momentum_buffer'] = torch.zeros(1, 2)
pending.submit(lambda loss: print('unexpected'), report)
pending = compiled(x, y)
sgd.state.clear()
pending.submit(lambda loss: print('unexpected'), report)
adam = torch.optim.Adam(model.parameters())
compiled, eager = make(adam)
compiled(x, y).submit(lambda loss: print(adam.state[id(model.weight)]['step']))
pending = compiled(x, y)
eager(x, y)
pending.submit(lambda loss: print('unexpected'), report)
print(adam.state[id(model.weight)]['step'], torch.equal(model.weight, before))
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "['momentum_buffer']",
            "GPU training result is stale; optimizer state changed before completion",
            "GPU training result is stale; optimizer state changed before completion",
            "1",
            "GPU training result is stale; optimizer changed before completion",
            "2 False",
        ]
    );
}

#[test]
fn graph_kernels_match_the_float32_reference_bit_for_bit() {
    // Every operation family of graph protocol version 2, run through the
    // tensor kernels (`_execute_kernels`, the native path without a host) and
    // through the pure-Python float32 reference (`execute_locally`) in the same
    // program: identical float32 storage bytes for every output, signed zeros
    // included. This is the contract behind `tools/python_corpus.py`, whose
    // programs print graph results under CPython and Zipp alike.
    let out = run(r#"
from zipp_gpu import Graph, execute_locally, _execute_kernels
import _zipp_tensor as _k

state = [11]
def lcg(n, scale, offset=0.0):
    out = []
    for _ in range(n):
        state[0] = (state[0] * 1103515245 + 12345) % 2147483648
        out.append(round((state[0] / 2147483648 * 2 - 1) * scale + offset, 5))
    return out

def check(family, g, **outputs):
    kern = _execute_kernels(g._program(outputs), True)
    ref = execute_locally(g.program(**outputs))
    seen = []
    for name in outputs:
        k, r = kern["outputs"][name], ref["outputs"][name]
        assert k["shape"] == r["shape"], (family, name, k["shape"], r["shape"])
        assert isinstance(k["data"], _k.Storage) and _k.size(k["data"]) == len(r["data"]), (family, name)
        assert _k.tobytes(k["data"]) == _k.tobytes(_k.from_flat("float32", r["data"])), (family, name, _k.to_list(k["data"])[:6], r["data"][:6])
        assert all(k["data"] is not other for other in seen), (family, name, "shared storage")
        seen.append(k["data"])
    assert kern["stats"] == ref["stats"] and kern["backend"] == ref["backend"], family
    print(family, "identical", len(outputs))

g = Graph()
col, row = g.tensor(lcg(64, 3.0), (64, 1)), g.tensor(lcg(10, 2.0), (1, 10))
mat, bias = g.tensor(lcg(640, 1.0), (64, 10)), g.tensor(lcg(10, 0.5))
cube, plane = g.tensor(lcg(24, 2.0), (2, 3, 4)), g.tensor(lcg(3, 1.0, 1.5), (3, 1))
check("broadcast", g, strided=col - row, tiled=mat + bias, mid=cube * plane, scalar=2.0 / (mat * mat + 1.0),
      ratio=col / row, flipped=row - col, negzero=-(mat * 0.0), minus=mat * -1.0, same=mat - mat, div=(cube + 5.0) / (plane * 2.0))

g = Graph()
x = g.tensor(lcg(97, 6.0) + [0.0, -0.0, 1e-4, -1e-4, 5.9, -5.9])
check("unary", g, exp=x.exp(), log=(x * x + 1.0).log(), sqrt=(x * x).sqrt(), tanh=x.tanh(), sigmoid=x.sigmoid(),
      gelu=x.gelu(), gelu_grad=x.gelu_grad(), relu=x.relu(), positive=x.positive(), neg=-x)

g = Graph()
t = g.tensor(lcg(60, 4.0), (3, 4, 5))
scalar = g.tensor(2.5)
check("reduce", g, whole=t.sum(), whole_mean=t.mean(), keep=t.sum(keepdim=True), keep_mean=t.mean(keepdim=True),
      s0=t.sum(0), s1=t.sum(1), s2=t.sum(2), s1k=t.sum(1, keepdim=True), m0=t.mean(0), m2k=t.mean(-1, keepdim=True),
      rank0=scalar.sum(0), rank0k=scalar.mean(0, keepdim=True), vec=g.tensor(lcg(13, 9.0)).sum(0))

g = Graph()
logits, small, deep = g.tensor(lcg(60, 5.0), (6, 10)), g.tensor(lcg(7, 3.0)), g.tensor(lcg(24, 4.0), (2, 3, 4))
check("softmax", g, sm=logits.softmax(), lsm=logits.log_softmax(), sm1=small.softmax(), lsm1=small.log_softmax(),
      sm3=deep.softmax(), lsm3=deep.log_softmax(-1))

g = Graph()
a, b = g.tensor(lcg(192, 1.0), (8, 24)), g.tensor(lcg(144, 1.0), (24, 6))
a3, b3, b2 = g.tensor(lcg(24, 1.5), (2, 3, 4)), g.tensor(lcg(40, 1.5), (2, 4, 5)), g.tensor(lcg(20, 1.5), (4, 5))
a1, a2 = g.tensor(lcg(12, 1.5), (1, 3, 4)), g.tensor(lcg(12, 1.5), (3, 4))
check("matmul", g, plain=a @ b, batched=a3 @ b3, right_matrix=a3 @ b2, left_matrix=a2 @ b3, left_one=a1 @ b3, chained=(a @ b).T @ a)

g = Graph()
logits = g.tensor(lcg(60, 5.0), (6, 10))
targets = [3, 0, 9, 4, 4, 7]
check("cross_entropy", g, loss=logits.cross_entropy(targets), grad=logits.cross_entropy_grad(targets),
      loss1=(logits * 3.0).cross_entropy(targets), grad1=(logits * 3.0).cross_entropy_grad(targets))

g = Graph()
raw = g.tensor(lcg(24, 2.0), (2, 3, 4))
storage_input = g.tensor(_k.from_flat("float32", lcg(6, 2.0)), (2, 3))
check("shape", g, perm=raw.permute(2, 0, 1), swapped=raw.transpose(0, 2), flat=raw.reshape(4, 6), inferred=raw.reshape(-1),
      matrix_t=storage_input.T, raw=raw, again=raw, view=raw.reshape(24), stored=storage_input, stored_view=storage_input.reshape(6))

g = Graph()
p, grad = g.tensor(lcg(40, 1.0), (5, 8)), g.tensor(lcg(40, 0.3), (5, 8))
m, v = g.tensor(lcg(40, 0.1), (5, 8)), g.tensor([abs(x) for x in lcg(40, 0.01)], (5, 8))
p1, m1, v1 = g.adam(p, grad, m, v, lr=0.01, step=1)
p7, m7, v7 = g.adam(p1, grad, m1, v1, lr=0.001, betas=(0.9, 0.999), eps=1e-8, step=7)
pb, mb, vb = g.adam(p, grad, m, v, lr=0.05, betas=(0.3, 0.5), eps=0.0, step=3)
buf = g.momentum_update(m, grad, 0.9, dampening=0.1)
check("optimizer", g, sgd=g.sgd_update(p, grad, 0.1), decayed=g.sgd_update(p, grad + p * 0.01, 0.05), buf=buf,
      nesterov=g.sgd_update(p, grad + buf * 0.9, 0.05), p1=p1, m1=m1, v1=v1, p7=p7, m7=m7, v7=v7, pb=pb, mb=mb, vb=vb)

# A whole training step: dense layers, GELU, fused cross-entropy, Adam.
g = Graph()
xs, ys = g.tensor(lcg(36, 1.0), (9, 4)), [i % 3 for i in range(9)]
w1, b1, w2, b2 = g.tensor(lcg(24, 0.5), (4, 6)), g.tensor(lcg(6, 0.1)), g.tensor(lcg(18, 0.5), (6, 3)), g.tensor(lcg(3, 0.1))
pre = xs @ w1 + b1
hidden = pre.gelu()
logits = hidden @ w2 + b2
delta = logits.cross_entropy_grad(ys)
back = (delta @ w2.T) * pre.gelu_grad()
grads = [xs.T @ back, back.sum(0), hidden.T @ delta, delta.sum(0)]
outputs = {"loss": logits.cross_entropy(ys), "probs": logits.softmax(), "lsm": logits.log_softmax().mean(1, keepdim=True)}
for i, (param, gr) in enumerate(zip([w1, b1, w2, b2], grads)):
    outputs["p%d" % i], outputs["m%d" % i], outputs["v%d" % i] = g.adam(param, gr, g.zeros(param.shape), g.zeros(param.shape), lr=0.05, step=1)
check("training_step", g, **outputs)
"#)
    .unwrap();
    assert_eq!(
        out,
        [
            "broadcast identical 10",
            "unary identical 10",
            "reduce identical 13",
            "softmax identical 6",
            "matmul identical 6",
            "cross_entropy identical 4",
            "shape identical 10",
            "optimizer identical 13",
            "training_step identical 15"
        ]
    );
}

#[test]
fn eager_gelu_default_is_the_exact_erf_form_and_tanh_matches_pytorch() {
    // Golden values from CPU PyTorch 2.11 (`py -3.11`): F.gelu with the
    // default approximate="none" (exact erf) and approximate="tanh", forward
    // and backward, on the same points. The erf approximation the kernels
    // share is good to about 1e-7, so 2e-6 separates the two forms (they
    // differ by up to 4e-4 here) without demanding libm equality.
    let out = run(r#"
import torch
import torch.nn.functional as F
points = [-3.0, -1.5, -0.5, 0.0, 0.25, 0.75, 2.0, 4.0]
expected = {
    "none": ([-0.0040502, -0.1002109, -0.1542688, 0.0, 0.1496766, 0.5800295, 1.9544997, 3.9998736],
             [-0.0119456, -0.1274692, 0.1325049, 0.5, 0.6953733, 0.9992258, 1.0852319, 1.0005037]),
    "tanh": ([-0.0036374, -0.1004284, -0.154286, 0.0, 0.1496754, 0.5799606, 1.9545977, 3.9999299],
             [-0.0115842, -0.1277108, 0.1326301, 0.5, 0.6953541, 0.9989383, 1.0860993, 1.000335]),
}
for form, (values, grads) in expected.items():
    x = torch.tensor(points, requires_grad=True)
    y = F.gelu(x) if form == "none" else F.gelu(x, approximate=form)
    y.sum().backward()
    worst = max(max(abs(a - b) for a, b in zip(y.tolist(), values)), max(abs(a - b) for a, b in zip(x.grad.tolist(), grads)))
    print(form, worst < 2e-6, torch.allclose(torch.nn.GELU(approximate=form)(x), y))
try:
    F.gelu(torch.ones(2), approximate="foo")
except RuntimeError as error:
    print(error)
"#)
    .unwrap();
    assert_eq!(out, ["none True True", "tanh True True", "approximate argument must be either none or tanh."]);
}
